dimforge/nalgebra

- src/structs/dvec.rs
- src/structs/dvec_macros.rs
- src/structs/mat_macros.rs
- src/structs/spec/vec.rs
- src/structs/spec/vec0.rs
- src/structs/vec_macros.rs
The version is rustc 0.13.0-dev (cd614164e 2015-01-02 02:31:12 +0000).
The fixed array syntax was changed from [x, ..3] to [x; 3].
> Update to latest Rust

- src/macros/assert.rs
- src/structs/dmat.rs
- src/structs/dvec_macros.rs
- src/structs/iso_macros.rs
- src/structs/mat_macros.rs
- src/structs/quat.rs
- src/structs/rot_macros.rs
- src/structs/spec/vec0.rs
- src/structs/vec_macros.rs
- src/traits/operations.rs
- tests/assert.rs
See issue #60.
Background reading:  https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/
approx_eq_ulps() allows specification of epsilon as an integer number
of Units in the Last Place (ULPs) difference between the two floating
point values
default approx_ulps() is set to 8.
approx_eq() function continues to use epsilon method, although I
recommend further commits and a migration towards the ULPs method.
> ApproxEq trait enhanced with ULPs method of specifying closeness:

- src/lib.rs
- src/linalg/decompositions.rs
- src/structs/dmat.rs
- src/structs/dvec.rs
- src/structs/dvec_macros.rs
- src/structs/iso_macros.rs
- src/structs/mat_macros.rs
- src/structs/pnt_macros.rs
- src/structs/quat.rs
- src/structs/rot.rs
- src/structs/rot_macros.rs
- src/structs/spec/identity.rs
- src/structs/spec/mat.rs
- src/structs/spec/vec.rs
- src/structs/spec/vec0.rs
- src/structs/vec_macros.rs
- src/traits/geometry.rs
- src/traits/operations.rs
- src/traits/structure.rs
Version of rustc: 0.13.0-nightly (c6c786671 2015-01-04 00:50:59 +0000).
This also changes the `Cross` trait to use an associated type for its output (this is needed for `ncollide`).
Many other traits will benefit from associated type, but I delay those modifications until things start to break less frequently on the language side.
> Update to the last rust-nightly.

- src/lib.rs
- src/structs/dmat.rs
- src/structs/dvec.rs
- src/structs/dvec_macros.rs
- src/structs/spec/vec.rs
- src/structs/spec/vec0.rs
- src/structs/vec_macros.rs
- src/traits/geometry.rs
- src/traits/structure.rs
`Fn` was the wrong way to go because a closure like `|y| x = y` isn't a valid `Fn`, but it's a valid `FnMut` (because it captures the mutable external state of `x`).
> Change Fn to FnMut

- .travis.yml
- Cargo.toml
- src/lib.rs
- src/structs/dmat.rs
- src/structs/dvec.rs
- src/structs/dvec_macros.rs
- src/structs/iso.rs
- src/structs/iso_macros.rs
- src/structs/mat.rs
- src/structs/ortho.rs
- src/structs/persp.rs
- src/structs/pnt.rs
- src/structs/pnt_macros.rs
- src/structs/quat.rs
- src/structs/rot.rs
- src/structs/vec.rs
- src/structs/vec_macros.rs
- tests/arbitrary.rs
All types in nalgebra can now be used for quickcheck-style testing as an optional feature. `Rot4` and `Iso4` had to be left out, since `Rot4` apparently lacks a working constructor.
The test suite could, in principle, now be migrated to use quickcheck to, as this helps to detect and prevent a large range of bugs.
> Implement Arbitrary for (almost) all types

- src/lib.rs
trivial fix to remove deprecation warning in rustc 1.0.0-nightly (44a287e6e 2015-01-08 17:03:40 -0800):
src/lib.rs:86:12: 86:28 warning: feature is deprecated and will only be available for a limited time, please rewrite code that relies on it
src/lib.rs:86 #![feature(old_orphan_check)]
^~~~~~~~~~~~~~~~
> fix warning from unneeded old_orphan_check

- src/traits/structure.rs
BaseNum is described in the comment as basic integral numeric trait but it's only implemented for floats. also fixes the comment that was broken in a PR i sent some days ago with a find and replace for int -> isize
> impl BaseNum for integers

- src/traits/operations.rs
- tests/assert.rs
Just as the standard library's PartialEq is implemented for reference types, the ApproxEq trait should be implemented on them as well. This is mostly an ergonomic improvement for certain testing situations, where a method yields a reference. For non-copy types it allows using the assert_approx_… macros, which would otherwise not be possible.
> Implement AssertEq for reference types

- src/lib.rs
- src/linalg/decompositions.rs
- src/structs/dmat.rs
- src/structs/dvec_macros.rs
- src/structs/iso_macros.rs
- src/structs/mat_macros.rs
- src/structs/quat.rs
- src/structs/rot.rs
- src/structs/rot_macros.rs
- src/structs/spec/complex.rs
- src/structs/spec/identity.rs
- src/structs/spec/mat.rs
- src/structs/spec/vec.rs
- src/structs/spec/vec0.rs
- src/structs/vec_macros.rs
- src/traits/geometry.rs
- src/traits/operations.rs
- src/traits/structure.rs
Fixes #52.
This renames pairs of methods like `normalize_cpy`, `normalize` to `normalize`
and `normalize_mut`. Note that the previous in-place operations had the same
name that now belongs to the copy operations. Therefore this is a breaking
change.
On a similar note, the `Quat::conjugate` method was also renamed to
`conjugate_mut` and a new copying method has taken its place. This appears to
be a similar issue (apart from the lack of the copy operation) and thus was
dealt with here, too.
> Rename similar in-place and copy methods

- src/lib.rs
The associated type bound here is not interpreted correctly. This is likely due to the ICE described in rust-lang/rust#20413.
Note, that this may lead to a loss of type inference using that function.
> Workaround internal compiler error

- Cargo.toml
- benches/construction.rs
- benches/dmat.rs
- benches/mat.rs
- benches/quat.rs
- benches/vec.rs
- src/lib.rs
- src/structs/dmat.rs
- src/structs/dvec.rs
- src/structs/dvec_macros.rs
- src/structs/iso.rs
- src/structs/mat.rs
- src/structs/pnt.rs
- src/structs/quat.rs
- src/structs/rot.rs
- src/structs/spec/vec0.rs
- src/structs/vec.rs
- src/structs/vec_macros.rs
- tests/arbitrary.rs
- tests/assert.rs
- tests/mat.rs
- tests/quat.rs
- tests/vec.rs
Most importantly, the rand module has been removed from the standard library. With this change, `nalgebra` now depends on the [new crates.io module](https://crates.io/crates/rand).
Apart from that all warnings were cleared out, leading to the discovery of a bug in `UnitQuat::new_with_quat`, which has been fixed.
> Adapt to upstream changes

- src/linalg/decompositions.rs
- src/structs/dmat.rs
- src/structs/dvec.rs
- src/structs/dvec_macros.rs
- src/structs/mat_macros.rs
- src/structs/vec_macros.rs
Mostly related to the `us` → `usize` suffix renaming. It turns out that none of the suffixes are required any more, as the type inference appears to have improved in that regard. There were also parantheses around range terms that are not required any more.
Finally the `[]` syntax has been deprecated and thereby removed.
> Fix a number of warnings

- src/structs/dmat.rs
- src/structs/dvec_macros.rs
- src/structs/iso.rs
- src/structs/mat.rs
- src/structs/mat_macros.rs
- src/structs/pnt.rs
- src/structs/quat.rs
- src/structs/rot.rs
- src/structs/vec.rs
- tests/mat.rs
- tests/quat.rs
- tests/vec.rs
Same as from previous PR, but now also includes `Iso` and `Rot`. Addresses #85. Depends on #98.
> Add [repr(C)] to structs likely to be used in FFI

- Cargo.toml
`rand` has not yet been updated to latest Rust, but it's been bumped to 0.3 and it's unlikely that 0.2 will be updated.
> Update to rand 0.3

- src/lib.rs
- src/structs/dmat.rs
Resolves this error, which is fallout from
https://github.com/rust-lang/rust/pull/23673:
```
src/structs/dmat.rs:501:43: 501:74 error: type annotations required: cannot resolve `<f64 as core::ops::Div<_>>::Output == f64` [E0284]
src/structs/dmat.rs:501         let normalizer: N    = Cast::from(1.0f64 / Cast::from(self.nrows));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Signed-off-by: Anders Kaseorg <andersk@mit.edu>
> Add type annotation required by rustc 2015-03-31

- src/structs/iso.rs
- src/structs/iso_macros.rs
- src/structs/quat.rs
- src/structs/spec/mat.rs
- src/traits/structure.rs
As per rust-lang/rust#23945, `Neg` is no longer implemented for unsigned types.
> Remove Neg from BaseNum

- src/traits/structure.rs
> frac_2_sqrt_pi renaming

- benches/common/macros.rs
- benches/dmat.rs
- src/lib.rs
- src/structs/dmat.rs
- src/structs/dvec.rs
- src/structs/iso.rs
- src/structs/mat.rs
- src/structs/pnt.rs
- src/structs/quat.rs
- src/structs/rot.rs
- src/structs/spec/identity.rs
- src/structs/spec/vec.rs
- src/structs/spec/vec0.rs
- src/structs/vec.rs
- src/structs/vec_macros.rs
- src/traits/mod.rs
- src/traits/structure.rs
Remove our own definitions of those traits.
Also fixes test-related attributes to make them compile again.
> Use the `Zero` and `One` traits from the `num` crate.

- src/structs/mat_macros.rs
Found this little bug, it's picked up by a new linter in the nightly
> This reference should not be mut

- src/lib.rs
- src/structs/quat.rs
- src/structs/rot.rs
- src/structs/spec/vec.rs
- src/structs/vec_macros.rs
- src/traits/geometry.rs
- src/traits/mod.rs
- tests/mat.rs
- tests/quat.rs
- tests/vec.rs
Use `::angle_between` or `.angle_to`  to compute the rotation angle between two vectors/rotation
matrices/unit quaternions.
Use `::rotation_between` or `.rotation_to` to compute the rotation matrix/unit quaternion to
transform a vector/rotation matrix/uniq quaternion to another.
Fix #130
> Add the `RotationTo` trait to compute the delta rotation between two elements.

- .travis.yml
Benchmarks require `#[feature(test)]` which is not supported by the stable branch.
> Don't run benchmarks on travis.

- src/structs/dmat.rs
- tests/mat.rs
Currently, the std operations (`Mul`, `Add` and `Sub`) consume both the lhs and rhs `DMat`s even though it is not always necessary or desired. This means a user must clone the `DMat` on the occasion that they only have access to the `DMat` by reference. As an example, the following isn't allowed:
```Rust
let NeuralNetwork { ref input_mat, ref weight_mat, .. } = *net;
let activity = *input_mat * *weight_mat; // error: cannot move out of borrowed content
```
This PR implements the std operations for `&'a DMat`, allowing the above example to work like so:
```Rust
let NeuralNetwork { ref input_mat, ref weight_mat, .. } = *net;
let activity = input_mat * weight_mat;
```
Specifically, the following are now possible:
```Rust
(&mat_a) * mat_b;
mat_a * (&mat_b);
(&mat_a) * (&mat_b);
mat_a + …
```
> Allow for non-consuming std operations on DMat. Added DMat multiplication test.

- Cargo.toml
- Makefile
- src/structs/spec/identity.rs
Because most of their methods did not make sence for the (constant) identity transformation, they were set to `panic!` at runtime whenever the user tried to use them. Instead, it is much safer to completely forbid their use by removing the related trait implementation.
See sebcrozet/ncollide#87.
> Remove implementations of `Rotation`, `Translation` and `Transformation` for the `Identity` type.

- src/structs/dmat.rs
- tests/mat.rs
The RowSlice implementation for DMat allocates and returns a DVec of length self.nrows independent of the size of the slice.
These changes resolve the bug and add test cases for the DMat implementations of RowSlice and ColSlice.
> Fix wrong allocated vector length in RowSlice for DMat

- src/structs/dmat.rs
DMat was unable to use the Debug trait if the value stored inside did not have the Display trait. This meant it could not be displayed or used in an assertion.
> Removed Display trait requirement from Debug method for DMat.

- src/lib.rs
- src/linalg/decompositions.rs
- src/linalg/mod.rs
- tests/mat.rs
I implemented a function that transforms a given matrix to Hessenberg form which allows to efficiently compute the QR decompositions with less operations than with the full Householder approach. Additionally, the Wilkinson shift is introduced to improve the convergence rate.
Unfortunately, this algorithm and the original algorithm can only be used with symmetric matrices since general matrices may possess complex eigenvalues. This case is much more complicated and requires more sophisticated algorithms which can be addressed later.
> Improved QR algorithm convergence

- src/linalg/decompositions.rs
- tests/mat.rs
As pointed out by @MichaelRiss, my previous QR algorithm did not handle a possible division by zero which may arise at computing the eigenvalues of diagonal matrices. This pull request fixes this bug and adds a test case for random diagonal matrices.
This patch should pass the test case provided in #163 and fix the issue presented in sebcrozet/nphysics#43
> Fix QR algorithm for diagonal matrices

- src/structs/mat_macros.rs
for example:
```rust
let m4: Mat4<f32> = one();
let m3: Mat3<f32> = from_homogeneous(&m4);
```
used 4 as the boundary of the for loop which made it panic
> mat_macros: from_homogeneous_impl was using dimension of src not dst

- src/structs/dmat_macros.rs
- src/structs/mat_macros.rs
- src/structs/vec_macros.rs
- src/structs/vecn_macros.rs
To be specific, support is added for `N op T<N>` where `N` is `f32` or `f64`, `op` is one of `+` `-` `*`, and `T` is one of the `Vec`, `DVec`, `Mat`, or `DMat` generic types. These are all cases where `T<N> op N` is already supported.
*   Except for `f32 * Vec3<f32>`, which works fine :) the rest of this is untested.
*   The code I'm touching in `src/mat_macros.rs` seems to be dead code! I can remove it or just leave it alone instead, just let me know what to do...
> Support `f64 * Vec3<f64>` and so on. Fixes #182.

- benches/common/macros.rs
Previously, `cargo bench` had been failing out with, (e.g.)
```error[E0277]: the trait bound `&na::Quaternion<f32>: std::ops::Mul<na::Quaternion<f32>>` is not satisfied```
> Fix benchmark macro `bench_binop`

- src/core/componentwise.rs
The documentation currently says "Componentwise matrix multiplication.", no matter what the operation actually does. The attached commit fixes this by introducing more parameters to the macro, through which documentation strings can be passed. I'm not at all sure that this is the appropriate solution, but it's all I could come up with.
> Allow for documentation strings in macro component_binop_impl.

- Cargo.toml
This link doesn't seem to be correct and this is leading to the link on crates.io pointing to the wrong place, I believe.
> Fixing the documentation link in Cargo.toml

- docs/getting_started.md
> Fixing a typo in Getting Started about cargo features

- src/core/inverse.rs
- tests/matrix_inverse.rs
Resolves #244. I couldn't find any existing tests for `try_inverse` at all, so I took the liberty to add some very basic tests for a single example of a few different dimensions. Let me know if you don't want them!
> Relax invertibility check for Matrix::try_inverse

- src/core/conversion.rs
`IntoIterator` for `Matrix<...>` (without reference) will be harder to implement.
Partially addresses #241.
> Implement IntoIterator for &Matrix and &mut Matrix

- Cargo.toml
I needed this to serialise `UnitComplex`.  Does it seem reasonable?
> Enable serde on num-complex

- src/core/dimension.rs
- src/core/matrix.rs
- src/core/unit.rs
- src/geometry/orthographic.rs
- src/geometry/perspective.rs
- src/geometry/point.rs
- src/geometry/quaternion.rs
- src/geometry/rotation.rs
- src/geometry/transform.rs
- src/geometry/translation.rs
- tests/serde.rs
I think I got everything; let me know if not.
I deliberately passed on intelligent handling of nrows/ncols in `MatrixVec` for now because it seems considerably less trivial.
In the future, these impls could be replaced by a macro, or better yet, attribute-based support in serde for forwarding implementations.
Fixes #249
> Remove gratuitous indirection in serialization impls

- src/lib.rs
- tests/core/mod.rs
- tests/lib.rs
The tests can now be run without the abomonation feature. Also fixes a bug in the feature flagging for abomonation.
This issue came up in the discussion of #283.
@WaDelma @ChristopherRabotin does this take care of your issue?
> Fix feature flagging for abomonation-serialize

- docs/decompositions_and_lapack.md
- docs/quick_reference.md
- docs/vectors_and_matrices.md
"Below" should only have one 'L' in it (this also occurs in the autogenerated rust docs, but that requires a separate PR against master to be fixed).
> Fix spelling of "below" in gh-pages

- nalgebra-lapack/src/svd.rs
- src/core/blas.rs
- src/geometry/quaternion.rs
- src/linalg/svd.rs
Counterpart to #296 - this fixes typos in the method documentation (I also fixed some code comments that don't get picked up by rustdoc - I apologize if doing so comes off as nitpicking).
> Fix spelling of "below" (in method documentation)

- src/geometry/quaternion.rs
- src/geometry/rotation_specialization.rs
- tests/geometry/quaternion.rs
- tests/geometry/rotation.rs
Addresses #243 by implementing `to_euler_angles` methods for [`Rotation3`](http://nalgebra.org/rustdoc/nalgebra/geometry/type.Rotation3.html) and [`UnitQuaternion`](http://nalgebra.org/rustdoc/nalgebra/geometry/type.UnitQuaternion.html). These functions complement the `from_euler_angles` [provided by `Rotation3`](http://nalgebra.org/rustdoc/nalgebra/geometry/type.Rotation3.html#method.from_euler_angles) and [`UnitQuaternion`](http://nalgebra.org/rustdoc/nalgebra/geometry/type.UnitQuaternion.html#method.from_euler_angles).
> Implement to_euler_angles for Rotation3 and UnitQuaternion

- src/core/matrix.rs
- tests/core/matrix.rs
Fix #308 
This is not related to this issue, but I tried fixing the `soooo ugly!` problem. We would need a tool to get the first, second and third element, like `.x`, `.y` `.z` They are not available in this function. Do you now where they are defined? I might try the `FIXME: use specialization instead of an assertion.` when I have some free time.
> Row vector cross product

- docs/points_and_transformations.md
The missing `</div>` was borking the markdown for the 'Transformations' section of the guide. 
This fixes #322.
> Insert missing `</div>` after code snippet in 'Points and Transformations' guide.

- CHANGELOG.md
- src/core/construction.rs
> Add ::from_distribution to build a matrix from a user-provided distribution

- benches/core/matrix.rs
- src/base/construction.rs
Hi!
First, thank you for your librairies, they are great!
After investigating the performances of [the code from a friend on the forum](https://discourse.nphysics.org/t/efficient-ways-of-computing-a-centered-gradient/204), I realized that the `from_fn` function was quite slow due to the fact that matrices are stored by columns, but the iteration is done by rows.
I also added a benchmark to see the performance improvements:
Original version:
```
test core::matrix::mat100_from_fn :     7,736 ns/iter (+/- 246)
test core::matrix::mat500_from_fn : 1,085,050 ns/iter (+/- 192,820)
```
This PR version:
```
test core::matrix::mat100_from_fn:   2,796 ns/iter (+/- 189)
test core::matrix::mat500_from_fn: 650,736 ns/iter (+/- 16,264)
```
> Changed loops order in from_fn_generic

- src/base/blas.rs
Currently the equivalents to numpy's `argmax()` and `argmin()` only exist for the min/max _absolute_ values in a Matrix. This implements non-abs variations of nalgebra's `aimax()` and `aimin()`.
> Add imax/imin()

- CHANGELOG.md
- src/base/construction.rs
- src/geometry/quaternion_construction.rs
- src/geometry/rotation_specialization.rs
- src/geometry/unit_complex_construction.rs
This replaces the presumably non-uniform `Standard` distribution implementations for `UnitQuaternion` and `Rotation3` with uniform sampling algorithms taken from Graphics Gems III. While I was at it I also dropped in an implementation for `Unit<VectorN>`.
The implementation bounds for the pre-existing distributions were modified to replace `Standard` with `OpenClosed01`, which is arguably a breaking change. Although this is approximately a no-op for f32/f64, it's unclear what `Standard` might mean for more exotic types, and hence I feel it's appropriate to make the requirements of the algorithms used more explicit.
An alternative approach would be to introduce one or more new unit structs implementing `Distribution` for these algorithms, preserving the pre-existing `Standard` impls for …
> Uniformly distributed random rotations, unit vectors

- nalgebra-lapack/src/cholesky.rs
- nalgebra-lapack/src/eigen.rs
- nalgebra-lapack/src/hessenberg.rs
- nalgebra-lapack/src/lu.rs
- nalgebra-lapack/src/qr.rs
- nalgebra-lapack/src/schur.rs
- nalgebra-lapack/src/svd.rs
- nalgebra-lapack/src/symmetric_eigen.rs
- src/geometry/isometry.rs
- src/geometry/orthographic.rs
- src/geometry/perspective.rs
- src/geometry/point.rs
- src/geometry/quaternion.rs
- src/geometry/rotation.rs
- src/geometry/similarity.rs
- src/geometry/transform.rs
- src/geometry/translation.rs
- src/linalg/bidiagonal.rs
- src/linalg/cholesky.rs
- src/linalg/eigen.rs
- src/linalg/full_piv_lu.rs
- src/linalg/hessenberg.rs
- src/linalg/lu.rs
- src/linalg/permutation_sequence.rs
- src/linalg/qr.rs
- src/linalg/schur.rs
- src/linalg/svd.rs
- src/linalg/symmetric_eigen.rs
- src/linalg/symmetric_tridiagonal.rs
> Fix compilation errors when the serde-serialize feature is enabled.

- ci/test.sh
- tests/linalg/cholesky.rs
> Fix compilation of test when arbitrary is enabled but not `debug`.

- src/base/matrix.rs
- src/geometry/quaternion.rs
- src/lib.rs
No new math here, just adding some common synonyms for the `norm()` functions.  I didn't know to look for the name `norm()` when browsing the docs so I got pretty confused.  The name `magnitude` is much more common in other math libraries I've used so these names are more intuitive to me.
> Add magnitude synonym functions for ease of use

- CHANGELOG.md
- src/base/cg.rs
- src/base/matrix.rs
- src/geometry/orthographic.rs
- src/geometry/perspective.rs
- src/geometry/quaternion.rs
As stated on the change log, this:
* adds `.dot` to quaternions.
* adds `.zip_zip_map` for iterating on three matrices simultaneously, and applying a closure to them.
* adds `.slerp` and `.try_slerp` to unit vectors.
* adds `.to_projective` and `.as_projective` to `Perspective3` and `Orthographic3` in order to
use them as `Projective3` structures (related to #392).
> Rollup of minor feature additions

- nalgebra-glm/src/aliases.rs
Was reading through the docs for the new GLM library (which looks fantastic, by the way - looking forward to trying it out!) and spotted a very small typo/copy and paste error  - it says that `Mat4` is a 4x3 matrix, rather than a 4x4 matrix.
> Fix typo in GLM Mat4 docs

- src/base/swizzle.rs
- tests/core/matrix.rs
> Use typenum type-level integer for swizzle dimension comparison.

- src/base/unit.rs
Just an idea I had after writing an API that takes `&Unit<Vector3<f64>>`; not sure if it's a good one. Note that `#[repr(transparent)]` was stabilized in 1.28.
> Introduce Unit::from_ref_unchecked

- src/base/conversion.rs
Resolves #342 by adding a bunch of `From` impls.
The fact that this couldn't be accomplished with one, more generic `From` impl has some consequences:
- All the additional impls add visual noise to the rustdoc.
- If you get used to using `.into()` for this purpose, you might be surprised that it stops working when you try to write more generic code over `MatrixMN`s (and you need to use the `into_owned` method instead).
> Add `Into` impls for converting `MatrixSlice`s into `MatrixMN`s

- nalgebra-glm/src/aliases.rs
By aliasing to the aliases defined within glm rather than going
directly to nalgebra types / aliases, we're able to improve the
experience of linking through the docs in the glm docs.
For example, with TVec1 defined in terms of TVec rather than Vector1,
then the docs link from TVec1 to TVec and we're able to better
explain the concepts at the glm level.
> Vector and quaternion alias improvements.

- src/linalg/svd.rs
- tests/linalg/svd.rs
Fix #358.
I changed the SVD methods to return a `Result` instead of an `Option`, since there are multiple types of errors. Knowing the error message might be useful.
I'm pretty new to rust and nalgebra, so I'm not sure if I'm doing everything right. For example, some questions in my mind right now:
* Should I also change the return types of the methods in `nalgebra-lapack/src/svd.rs`?
* Is is OK to return a `Result<MatrixMN<N, R, C>, &'static str>`:
* Should I return a custom error type?
* Is it OK for the lifetime of that string slice to be `static` (I'm pretty much a noob when it comes to lifetimes)? Should I return a `String` instead?
> Change the SVD methods to return a Result instead of panicking

- src/base/matrix.rs
- tests/core/matrix.rs
The implemented ordering is such that two matrices `A, B` are `Ordering::Less` iff. all `A[(i, j)] <= B[(i, j)]`. Similar rules apply for greater and equal. If there exists some components such that `A[(i1, j1)] < B[(i1, j1)])` and some other components such that `A[(i2, j2)] > B[(i2, j2)])`, then the ordering is `None`.
> Fix partial_cmp

- src/base/blas.rs
- src/base/componentwise.rs
- src/base/matrix.rs
This is a first step toward adding doc-tests and "see also" sections for all methods on nalgebra, just like @waywardmonkeys started to do on nalgebra-glm.
This PR only deals with doc-tests on BLAS operations.
> Add doc-test for BLAS operations.

- src/base/construction.rs
Addresses #378.
The implementation of `from_vec` simply wraps a call to `from_iterator_generic`. Because the standard library's implementation of `into_iter` [is specialized](https://github.com/rust-lang/rust/issues/46084#issuecomment-345524508) for the `.into_iter().collect<Vec<_>>()` case, this is equivalent to re-using the original Vec as storage.
> Introduces a `from_vec` constructor for `MatrixMN`.

- src/base/edition.rs
- src/base/matrix_vec.rs
My hope is that this is a step towards making concatenating vectors a little more ergonomic (see #446).
This PR is of narrow scope. `Extend` is only implemented for cases in which the operation is cheap. Right now this means:
- extend a matrix with new columns populated from an iterator
- extend a vector with new rows populated from an iterator
> Implement `Extend` for `Matrix`

- src/base/matrix.rs
- src/geometry/rotation.rs
- tests/core/matrix.rs
First attempt at #471. It seems that the disambiguation using `IsNotStaticOne` is working, but I can't get it to compile. 
Currently, I get the following error message:
```
error[E0277]: cannot multiply `<D as base::dimension::DimName>::Value` to `<D as base::dimension::DimName>::Value`
--> src/base/matrix.rs:833:1
|
833 | / impl<N: Scalar + One, D: DimNameAdd<U1> + IsNotStaticOne> MatrixN<N, D> {
834 | |
835 | |     /// Yields the homogeneous matrix for this matrix, i.e., appending an additional dimension and
836 | |     /// and setting the diagonal element to `1`.
...   |
844 | |
845 | | }
| |_^ no implementation for `<D as base::dimension::DimName>::Value * <D as base::dimension::DimName>::Value`
|
= help: the trait `std::ops::Mul` is not implemented for `<D as …
```
> RFC: to_homogeneous for MatrixN

- src/base/matrix_vec.rs
Very narrowly addresses @jturner314's [proximate issue](https://github.com/rustsim/nalgebra/issues/473#issuecomment-440038489) of getting the `Vec` out of a `Matrix` backed by a `Vec`.
This makes possible something that was previously impossible. However, this change isn't enough on it's own to achieve the ergonomic goals of #479.
> Implement `Into<Vec<N>>` for `MatrixVec<N, R, C>`

- src/base/swizzle.rs
- src/geometry/swizzle.rs
This is semantically equivalent, but improves the rendered documentation.
Previously, each swizzle method was contained in its own `impl`.
> Group swizzle methods by dimensional requirement.

- src/base/alias.rs
- src/base/array_storage.rs
- src/base/conversion.rs
- src/base/default_allocator.rs
- src/base/mod.rs
- src/base/storage.rs
- src/base/vec_storage.rs
This implements the renaming proposed in #470:
- `MatrixVec` → `VecStorage`
- `MatrixArray` → `ArrayStorage`
`MatrixVec` and `MatrixArray` remain as deprecated type aliases to `VecStorage` and `ArrayStorage`, respectively, so this may not actually be a breaking change.
> Storage type name reform.

- src/base/cg.rs
- src/base/unit.rs
- src/geometry/orthographic.rs
- src/geometry/perspective.rs
- src/geometry/quaternion.rs
- src/geometry/quaternion_construction.rs
- src/geometry/quaternion_conversion.rs
- src/geometry/quaternion_ops.rs
- src/geometry/reflection.rs
- src/geometry/rotation.rs
- src/geometry/rotation_conversion.rs
- src/geometry/rotation_ops.rs
- src/geometry/rotation_specialization.rs
- src/geometry/transform.rs
- src/geometry/transform_ops.rs
- src/geometry/unit_complex.rs
- src/geometry/unit_complex_ops.rs
- src/linalg/schur.rs
- tests/geometry/projection.rs
Implements #460 for `Unit`, `Rotation`, `Transform`, `Orthographic3` and `Perspective3`. In all cases, `unwrap()` is retained, but deprecated.
> Rename `unwrap` to `into_inner`.

- nalgebra-lapack/src/cholesky.rs
- src/base/blas.rs
- src/base/cg.rs
- src/base/componentwise.rs
- src/base/construction.rs
- src/base/conversion.rs
- src/base/edition.rs
- src/base/indexing.rs
- src/base/matrix.rs
- src/base/mod.rs
- src/base/ops.rs
- src/geometry/transform_ops.rs
- src/geometry/unit_complex_ops.rs
- src/linalg/cholesky.rs
- src/linalg/determinant.rs
- src/linalg/full_piv_lu.rs
- src/linalg/inverse.rs
- src/linalg/lu.rs
- src/linalg/solve.rs
This P.R. overloads matrix indexing in the same manner that the standard library overloads slice indexing.
Matrices can be indexed in three ways, each with different safety guarantees:
- `get` produces `Some` reference to the element(s) at the index, or `None` if the index is out of bounds
- `index` produces a reference to the element(s) at the index, or panics if the index is out of bounds
- `get_unchecked` produces a reference to the element(s) at the index, without bounds checking
Each of these has a corresponding `_mut` counterpart that produces a mutable reference to the element(s) at the given location.
Matrices can be indexed by a `usize`, or with any pair of `usize`, `Range<usize>`, `RangeFrom<usize>`, `RangeFull`, `RangeInclusive<usize>`, `RangeTo<usize>`, and …
> Overloaded Indexing Operations

- Cargo.toml
Those do not make sense on crates.io tarball.
> Exclude CI files

- src/base/ops.rs
Fixes #514. Supersedes #517.
Panic if the iterator is empty.
> `iter::Sum` for `DMatrix`

- src/geometry/quaternion.rs
Correct "looses" to "loses" in quaternion.rs documentation.
> Correct typo in quaternion documentation

- src/geometry/isometry.rs
- src/geometry/isometry_alga.rs
- src/geometry/quaternion.rs
- src/geometry/quaternion_alga.rs
- src/geometry/rotation.rs
- src/geometry/rotation_alga.rs
- src/geometry/similarity.rs
- src/geometry/similarity_alga.rs
- src/geometry/transform.rs
- src/geometry/transform_alga.rs
- src/geometry/translation.rs
- src/geometry/translation_alga.rs
- src/geometry/unit_complex.rs
- src/geometry/unit_complex_alga.rs
This adds `transform_point`, `transform_vector`,
`inverse_transform_point` and `inverse_transform_vector` as inherent
methods on the applicable geometric transformation structures, such
that they can be used without the need to import the `Transformation`
and `ProjectiveTransformation` traits from `alga`.
> Add the `transform` methods as inherent methods on geometric types

- src/base/matrix.rs
I'm currently using the slerp function to interpolate between frames in a skeletal animation,
Here is the actual result:
Comparing the nalgebra slerp with the gl-matrix slerp (which worked fine on the same animation), I noticed [some differences](https://github.com/toji/gl-matrix/blob/master/src/quat.js#L210-L216) with the nalgebra  implementation.
Same animation after the fix:
Let me know if you'd like some test around this case
> Fix matrix slerp function

- nalgebra-glm/src/ext/matrix_clip_space.rs
This adds the following to nalgebra-glm:
- infinite_perspective_rh_no
- infinite_perspective_rh_zo
- ~reversed_perspective_rh_no~
- reversed_perspective_rh_zo
- ~reversed_infinite_perspective_rh_no~
- reversed_infinite_perspective_rh_zo
Addresses #573
> Add some infinite and reversed perspectives.

- Cargo.toml
- src/base/construction_slice.rs
- src/lib.rs
Fixes #486.
The assertion is structured in a way that rules out false-positives. Each branch of the match arm ends in an assertion in the form:
```rust
index(i₀, j₀) != index(i₁, j₁)
```
If this expression evaluates to false, then `(i₀, j₀)` and `(i₁, j₁)` are, necessarily, examples of indices that will alias to the same linear index.
At a glance, it's a little less obvious that this assertion won't produce false-negatives. (This isn't as alarming as the possibility of a false-positive, since the current false-negative rate is 100%.) [The result of the assertion exactly matches the results of an exhaustive search for all combinations of rows, columns, row strides, and column strides ranging from 0 to 10.](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=7456bc83f93 …
> MatrixSliceMutMN: prevent aliased indices.

- src/lib.rs
I assume that you did a sed over the entire project, forgetting about the fact that "Real" is also used within the documentation. I haven't looked for other uses of "Real" other than this in the documentation.
> Fix incorrect documentation from `s/Real/&Field`

- Cargo.toml
- nalgebra-glm/src/common.rs
1. Downgraded rand for version 0.5 to avoid compilations errors with rand_jitter crate;
2. Changed std::mem to core::mem, to allow glm to compile with nostd. (Maybe it will need a cfg to switch between the two)
> Fix for nostd builds

- CHANGELOG.md
- Cargo.toml
- README.md
- nalgebra-glm/src/lib.rs
- nalgebra-lapack/Cargo.toml
- nalgebra-lapack/README.md
- nalgebra-lapack/src/lib.rs
- src/base/blas.rs
- src/geometry/quaternion_construction.rs
- src/geometry/rotation_specialization.rs
- src/lib.rs
When deploying some locally generated documentation to netlify, netlify was "helpfully" spewing out warnings such as this
```
6:05:35 PM: Mixed content detected in: /nalgebra/base/allocator/type.sameshapec.html
6:05:35 PM: --> insecure link urls:
6:05:35 PM:   - http://nalgebra.org/img/favicon.ico
```
And indeed, the [nalegbra site](https://www.nalgebra.org/rustdoc/nalgebra/index.html) itself has a similar warning about insecure content, at least in Firefox.
So this change just basically turns all of the http:// links to https:// including for some links to external sites in some of the comments, I think there was actually only 1 site that didn't have valid HTTPS.
> HTTPS All The Things

- src/base/ops.rs
Fixes for problems discussed in https://github.com/rustsim/nalgebra/issues/620
- Fixed functions returning wrong results
- ~~Added assert on empty matrices~~
- ~~Propagate `NaN` (or rather any value for which `PartialOrd::partial_cmp` returns `None`)~~
- Added doctests and documentation on the methods' behavior
> Fixes for [a,ca]min/max methods

- src/base/cg.rs
- tests/geometry/projection.rs
> Matrix::transform_point: correctly take the normalization term into account.

- src/base/cg.rs
Uncovered by a crater run in https://github.com/rust-lang/rust/pull/63565, the most recent v0.16.x version breaks when NLL is fully enabled. This PR is targeted to be based atop tag v0.16.13 (it's probably easiest to merge it manually, unless you want to create a branch for this PR to target).
> [v0.16] Fix NLL compatibility

- src/geometry/quaternion_construction.rs
When we want to compute the mean of multiple 3D rotations the documentation is scarce and the methods difficult. However, the paper of Markley et al.[1] describes an algorithm easy to implement to compute it. 
I implemented it for me but thought that it may be useful for others. I am still a rust beginner so my code may not be perfect so please feel free to correct it.
[1] Markley, F. L., Cheng, Y., Crassidis, J. L., & Oshman, Y. (2007). Averaging quaternions. Journal of Guidance, Control, and Dynamics, 30(4), 1193-1197.
> Added the mean computation of a vector of unit quaternions

- Cargo.toml
- nalgebra-lapack/Cargo.toml
- src/base/construction.rs
- src/lib.rs
With the new version of rand it is possible to use `Distribution<f32>` with `Matrix::from_distribution`, which is pretty handy.
* Bumped rand version to 0.7
* Added dependency to rand_distr
* Bumped quickcheck version to 0.9 (because of rand)
* Bumped rand_xorshift version to 0.2
> Rand 0.6 -> 0.7

- src/linalg/schur.rs
Due to rounding and possible loss of precision the lower left element of the 2x2 matrix
may be different from zero.
This optimization should fix issue #655. 
An example for this optimization can be found in Eigen code at the following [link](https://bitbucket.org/eigen/eigen/src/b58ba8bfb096e616cfe2fc39d1d94780174df809/Eigen/src/Eigenvalues/RealSchur.h#lines-419).
> Correct Schur decomposition for 2x2 matrices

- src/base/conversion.rs
- tests/core/conversion.rs
This PR adds some `From` implementations that allows us to construct matrix slices from matrix references. The main motivation for this is to allow for a simplified generic handling of matrix input when we don't care about whether the matrix sizes are static or dynamic:
```rust
fn solve(x: impl Into<DMatrixSliceMut<T>>, rhs: impl Into<DMatrixSlice<T>>) {
// Solve something and store result in `x`
}
```
Thanks to @sebcrozet for proposing the correct trait bounds to use to avoid problems with overlapping implementations.
One remark: I put the tests in `tests/core/conversion.rs`, but this module requires the `arbitrary` feature, which is unfortunate given that the test itself does not use `quickcheck`.
> Implement From<&Matrix> for MatrixSlice

- src/linalg/schur.rs
The eigenvalue problem is solved in two different method that use different methods
to calculate the discriminant of the solution to the quadratic equation.
Use the method whose computation is considered more stable.
Reference issue #655 in [comment](https://github.com/rustsim/nalgebra/issues/655#issuecomment-546641755)
> Use same algorithm to solve 2x2 eigenvalue problem

- Cargo.toml
- benches/core/matrix.rs
- benches/core/vector.rs
- benches/geometry/quaternion.rs
- benches/lib.rs
The rand crate removed IsaacRng in the 0.5 -> 0.6 transition, so the benchmarks that use it haven't compiled since 9c37c512039059281b210521cfd53e931f5fa0b5.
> Import IsaacRng from rand_isaac instead of rand.

- src/linalg/cholesky.rs
- src/linalg/solve.rs
- tests/linalg/cholesky.rs
Added code and test for cholesky decomposition update (see [issue 652](https://github.com/rustsim/nalgebra/issues/652)).
Also relaxed some traits from `StorageMut` to `Storage` in `solve.rs` methods (following [issue 667](https://github.com/rustsim/nalgebra/issues/667)).
My code to create a new matrix with one more/less row+column should be reviewed : it is correct but there is probably a more efficient way to do that using nalgebra internals.
The `insert_column` and `insert_row` methods take `&self` (where methods with the same name elsewhere in nalgebra take `self`) as it is the minimum required by the current implementation : it could be changed for homogenization purposes.
> Cholupdate

- src/base/blas.rs
- tests/core/blas.rs
One example would be performing simple matrix multiplication
over a division algebra such as quaternions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustsim/nalgebra/648)
> Fix Vector::axpy for noncommutative cases

- src/base/iter.rs
- src/base/storage.rs
When creating a matrix with only one zero dimension, we end up with a
matrix with a total size of zero, but a non-zero stride for elements.
While such a matrix can never actually have any elements, we need to be
careful with how we use the pointer associated with it.
Since such a pointer will always be dangling, it can never be used with `ptr.offset`,
which requires that the pointer be in-bounds or one passed the end of an
allocation. Violating this results in undefined behavior.
This commit adds in checks before the uses of `ptr.offset`. If we ever
need to offset from a pointer when our actual allocation size is zero,
we skip offsetting, and return the original pointer. This is fine
because any actual use of the original or offsetted pointer would
already be undefined behavior - we shoul …
> Don't call 'offset' on a dangling pointer

- src/base/vec_storage.rs
`Extend<N>` was already implemented, but nalgebra vectors/matrices give
iterators that give `&N`, not `N`, so implementing `Extend<&N>` as well makes
it easier to use.
It seems common practice to do so: The standard library's `Vec` also
implments Extend for both `T` and `&T`.
> Implement Extend<&N> for VecStorage.

- src/base/matrix.rs
- src/geometry/quaternion.rs
Fix #685.
This is a breaking change because this makes `slerp` unusable between vectors with complex components.
> Fix slerp for regular vectors.

- src/base/dimension.rs
- src/base/matrix.rs
- tests/core/matrix.rs
- tests/core/serde.rs
Addresses #674 (at least partly)
- `matrix_a == matrix_b` will no longer panic when shapes mismatch.
- In addition, comparison can be done if the number of rows / columns or storage are of different types (static vs dynamic, owned vs slice).
PartialEq trait for Matrices with `typenum`-typed number of rows and / or columns is not implemented symmetrically.
In other words, comparing two matrices with a `typenum`-typed Matrix on the left hand side of the `==` operator will work, but not if it is on the right hand side of the operator (compilation error).
This is because 
```
impl<
T: Dim,
U: ...,
B: ...
> PartialEq<UInt<U, B>> for T { ...}
```
violates Rust orphan rules for Trait implementation (see error `E0210`), and I could not find a way to work around it. Using a local struct to cover …
> Fix Matrix PartialEq bug and add some generalization

- src/linalg/givens.rs
The bug was introduced in b5f452087e3367b60dfc097078c5862f17bd8dc9
SVD sometimes fails trying to do `None.unwrap()` in `GivensRotation::new()`
> GivensRotation::new() should default to (I, 0)

- src/geometry/orthographic.rs
- src/geometry/perspective.rs
- src/geometry/transform_alias.rs
- src/lib.rs
* The `Perspective3` docs mentioned an "orthographic" projection where it should say "perspective"
* Replaced "an homogeneous" by "a homogeneous"
* Removed a double colon in lib.rs:54
> Small docs improvements

- src/base/cg.rs
- src/base/matrix.rs
- src/base/matrix_alga.rs
- src/base/norm.rs
- src/base/ops.rs
- src/geometry/isometry.rs
- src/geometry/isometry_alga.rs
- src/geometry/quaternion.rs
- src/geometry/rotation.rs
- src/geometry/rotation_alga.rs
- src/geometry/similarity.rs
- src/geometry/similarity_alga.rs
- src/geometry/transform.rs
- src/geometry/transform_alga.rs
- src/geometry/translation.rs
- src/geometry/translation_alga.rs
- src/geometry/unit_complex.rs
- src/geometry/unit_complex_alga.rs
- src/linalg/inverse.rs
Per #598, here's the first batch of #[must_use] annotations.
For now, I've only touched the non-mutable variants of *_mut functions. I may have missed some functions with multi-line declarations due to limitations of grep.
nalgebra and ncollide (including tests) compile without any new warnings.
There are probably other functions where annotations are useful, but I can't come up with a good guideline besides checking all 700+ public functions for purity, then tagging them all. Most functions are named properly (from_xx, to_xx) or return an entirely different type (like magnitude), making accidental misuse unlikely. But if you provide some guidance on which functions you'd like me to annotate, I'll make another pass.
> Add #[must_use] to all functions with a _mut variant (#598)

- src/base/statistics.rs
Currently the methods for row_sum and column_sum are tied up with the
code for statistical tests.  This means that to perform a row_sum or
column_sum requires the scalar type to inherit general field properties
and be SupersetOf<f64> to make quantities such as the mean value make
sense.  Consequently, row_sum() won't work on integer matricies.
This patch refactors the code to make the only requirement that the
scalar type be an additive monoid.  This is a more sensible requirement
for implemeting row and column sums.  As part of the refactoring, the
generic code for column and row wise folding has been separated from
the statistics code.
> Refactor row_sum() and column_sum() to cover more cases.

- src/linalg/cholesky.rs
Looks like the bound is unnecessary as there is no use of DimDiff in the implementation.
Integration tests are OK with it replaced by a simple Dim
> Unnecessary Trait bound DimSub<Dynamic> in impl Cholesky

- src/linalg/exp.rs
Because the CI was not configured properly, it did not run properly on  #708, causing a compilation failure when targeting no-std. This PR fixes this compilation issue.
> Fix compilation of matrix exponential when targetting no-std.

- nalgebra-glm/src/constructors.rs
- src/base/array_storage.rs
- src/base/construction_slice.rs
- src/geometry/quaternion.rs
- src/linalg/cholesky.rs
- src/linalg/solve.rs
- tests/core/edition.rs
- tests/core/matrix_slice.rs
- tests/core/mod.rs
- tests/linalg/eigen.rs
- tests/linalg/full_piv_lu.rs
- tests/linalg/inverse.rs
- tests/linalg/lu.rs
- tests/linalg/schur.rs
- tests/linalg/svd.rs
This adds the `Cholesky::new_unchecked` function that builds a Cholesky decomposition of a matrix that is assumed to already be positive-definite. This decomposition will not check that the matrix is actual positive-definite, hence the `_unchecked` suffix.
Not having these checks also remove all branching from the Cholesky decomposition, making it suitable to the use with SIMD types for, e.g., building four Cholesky decomposition at once using a `Matrix4<f32x4>`.
This also add unchecked lower-triangular solve functions.
> Add unchecked cholesky decomposition for AoSoA SIMD compatibility.

- src/base/blas.rs
- src/base/matrix.rs
- src/base/ops.rs
Previously, most dimension mismatch asserts used raw `assert!` and did not include the mismatching dimensions in the panic message. When using dynamic matrices, this led to somewhat-opaque panics such as:
```rust
let m1 = DMatrix::<f32>::zeros(2, 3);
let m2 = DMatrix::<f32>::zeros(5, 10);
m1 + m2 // panic: Matrix addition/subtraction dimensions mismatch.
```
This patch adds dimension information in the panic messages wherever doing so did not add additional bounds checks, mostly by simply changing `assert!(a == b, ...)` cases to `assert_eq!`. After:
```rust
// panic: assertion failed: `(left == right)`
//   left: `(2, 3)`,
//  right: `(5, 10)`: Matrix addition/subtraction dimensions mismatch.
```
Note that the `gemv` and `ger` were not updated, as they are called from within other …
> More verbose DMatrix dim asserts where possible.

- rustfmt.toml
The CI rustfmt checker uses `stable` rust, not `nightly`, but the config options in `rustfmt.toml` only work on nightly -- on stable, there are ignored with warnings. This means that devs running stable get a lot of warnings and devs running nightly will accidentally format in a way that the CI checker forbids. (specifically, using `where_single_line`). E.g.:
```
$ cargo +stable fmt -- --check
Warning: can't set `indent_style = Block`, unstable features are only available in nightly channel.
Warning: can't set `where_single_line = true`, unstable features are only available in nightly channel.
...etc
$ cargo +nightly fmt -- --check
-where
-    N: RealField,
-{
+where N: RealField {
...etc
```
Just removing the toml fixes this problem.
> Empty rustfmt.toml.

- Cargo.toml
- Makefile
- examples/matrixcompare.rs
- src/base/matrix.rs
- tests/core/matrixcompare.rs
- tests/core/mod.rs
~~**Note: this is not ready for merging. I'm posting it here for some initial feedback.**~~
*Update: This is in principle finalized and ready for merging (barring minor issues, see below)*.
This PR provides `matrixcompare` functionality for `nalgebra`. `matrixcompare` is a crate which aims to provide generic functionality for debug comparisons of matrices. A consumer crate like `nalgebra` only needs to define how many rows/columns a matrix has and how to fetch coefficients. Macros like `assert_matrix_eq!` then makes it easy to compare matrices with different kinds of comparators (absolute tolerance, relative tolerance etc.), which significantly simplifies debugging when writing unit tests involving linear algebra code.
`matrixcompare` is the result of extracting, rewriting and …
> Basic matrixcompare functionality

- .circleci/config.yml
- Cargo.toml
- nalgebra-glm/Cargo.toml
- nalgebra-lapack/Cargo.toml
- src/base/construction.rs
- src/lib.rs
- src/linalg/mod.rs
Because simba only enables `libm` if its `libm` feature is enabled, this PR adds the `libm` and `libm-force` feature to nalgebra in order to transitively enable the corresponding features on simba.
> Update to the latest simba version.

- src/geometry/point_coordinates.rs
Since both impls are #[inline], this should have no performance impact.
> Remove unsafe statement in Point::deref by forwarding to Vector.

- src/geometry/isometry.rs
- src/geometry/isometry_alias.rs
> Ensure Isometry implements Copy when targeting no-std.

- src/lib.rs
Looks like the docs are pointing to an outdated version, this is a fix for that
> Update version in docs header

- src/linalg/cholesky.rs
Follows on from #706 
The bound is unnecessary as there is no use of DimDiff in the implementation.
Integration tests are OK with it replaced by a simple Dim
> Remove unnecessary Trait bound DimSub<Dynamic> in fn cholesky(self)

- CHANGELOG.md
- Cargo.toml
- nalgebra-glm/Cargo.toml
- nalgebra-lapack/Cargo.toml
- src/base/construction.rs
- src/geometry/abstract_rotation.rs
- src/geometry/isometry.rs
- src/geometry/isometry_conversion.rs
- src/geometry/point.rs
- src/geometry/quaternion.rs
- src/geometry/quaternion_conversion.rs
- src/geometry/rotation.rs
- src/geometry/rotation_specialization.rs
- src/geometry/unit_complex.rs
This adds:
* the `.inverse_transform_unit_vector(v)` was added to `Rotation2/3`, `Isometry2/3`, `UnitQuaternion`, and `UnitComplex`.
It applies the corresponding rotation to a unit vector `Unit<Vector2/3>`.
* the `Point.map(f)` and `Point.apply(f)` to apply a function to each component of the point, similarly to `Vector.map(f)`
and `Vector.apply(f)`.
* the `Quaternion::from([N; 4])` conversion to build a quaternion from an array of four elements.
* the `Isometry::from(Translation)` conversion to build an isometry from a translation.
* the `Vector::ith_axis(i)` which build a unit vector, e.g., `Unit<Vector3<f32>>` with its i-th component set to 1.0 and the
others set to zero.
* the `Isometry.lerp_slerp` and `Isometry.try_lerp_slerp` methods to interpolate between two isometries using …
> Add various utility functions

- src/geometry/isometry_ops.rs
- src/geometry/quaternion.rs
- src/geometry/quaternion_ops.rs
- src/geometry/rotation_ops.rs
- src/geometry/similarity_ops.rs
- src/geometry/transform_ops.rs
- src/geometry/translation_ops.rs
- src/geometry/unit_complex_ops.rs
With those changes, there are no clippy errors left.
There's still a bunch of warnings though.
> Clippy fixes

- Cargo.toml
This removes `serde` default features (std) and allows `nalgebra` to be compiled with `serde-serialize` in a `no_std` environment.
> Make serde no_std compatible

- src/geometry/isometry_ops.rs
- src/geometry/similarity_ops.rs
- src/geometry/transform_ops.rs
- src/geometry/translation_ops.rs
My last PR did not fix all the clippy errors...
Probably (did not check) because I am not using latest rust (stuck with 1.43.0 atm)
This one hopefully does fix all errors.
> clippy: fix suspicious_op_assign_impl errors (false positives)

- tests/lib.rs
The `nalgebra` test suite at a minimum requires the `compare` and `debug` features. However, if these features are not passed in, the compilation fails with a bunch of errors from which it's very hard to discern what features are missing.
As discussed on Discord, this simple addition will give a compile-time error message if any of these two mandatory features are missing.
> Fail test compilation if mandatory features are missing

- src/base/alias.rs
- src/base/alias_slice.rs
- src/base/interpolation.rs
- src/base/unit.rs
- src/geometry/isometry.rs
- src/geometry/isometry_alias.rs
- src/geometry/isometry_construction.rs
- src/geometry/isometry_interpolation.rs
- src/geometry/mod.rs
- src/geometry/point.rs
- src/geometry/point_alias.rs
- src/geometry/point_construction.rs
- src/geometry/rotation.rs
- src/geometry/rotation_alias.rs
- src/geometry/rotation_construction.rs
- src/geometry/rotation_interpolation.rs
- src/geometry/rotation_specialization.rs
- src/geometry/swizzle.rs
- src/geometry/unit_complex.rs
- src/geometry/unit_complex_construction.rs
- tests/linalg/qr.rs
- tests/linalg/solve.rs
- tests/linalg/tridiagonal.rs
This is a second PR for documentation improvements. This time I focused on the `Unit` wrapper, as well as some of the geometric types:
- `Point`
- `Isometry`
- `UnitComplex`
- `Rotation`
Also, this adds to the documentation of most type aliases a bold text telling the reader not to forget to take a look at the aliased type too.
> Docs improvements - part 2

- src/base/array_storage.rs
- src/base/conversion.rs
- tests/core/serde.rs
> Add workaround for the deserialization of a matrix containing an enum.

- src/geometry/isometry.rs
It is more efficient (and less verbose) that way.
> Add a dedicated method for computing isometry1.inverse() * isometry2.

- src/base/unit.rs
- src/geometry/quaternion.rs
- src/geometry/quaternion_construction.rs
- src/geometry/quaternion_conversion.rs
- src/geometry/quaternion_ops.rs
- src/geometry/unit_complex.rs
- tests/geometry/quaternion.rs
The double-covering property should only be taken into account for `UnitQuaternion` instead of `Quaternion` itself.
As a result we no longer have the blancket impl of `PartialEq` for `Unit<T>`. Instead, it is implemented for each specialization of `Unit`. So this is a breaking change.
This also simplifies some of the trait bounds required by `Quaternion` for basic implementations like `Hash`, `PartialEq`, `Eq`, `Copy` and `Clone`. That way, we can auto-derive them.
> Fix the PartialEq impl for quaternions.

- src/geometry/dual_quaternion.rs
- src/geometry/dual_quaternion_construction.rs
- src/geometry/dual_quaternion_ops.rs
- src/geometry/mod.rs
- src/geometry/quaternion.rs
- src/geometry/quaternion_construction.rs
This commit introduces the `DualQuaternion` type, in line with the plan
laid out in [#487].
[#487]: https://github.com/dimforge/nalgebra/issues/487
> Introduce DualQuaternion type

- src/geometry/dual_quaternion.rs
- tests/core/matrixcompare.rs
> Serialize DQ to [N;8]

- benches/core/matrix.rs
- src/base/iter.rs
- tests/core/matrix.rs
Implements #794.
Also implements the [`FusedIterator`](https://doc.rust-lang.org/stable/core/iter/trait.FusedIterator.html) marker since it applies.
> impl DoubleEndedIterator for {MatrixIter, MatrixIterMut}

- src/linalg/col_piv_qr.rs
- src/linalg/decomposition.rs
- src/linalg/mod.rs
- src/linalg/udu.rs
- tests/linalg/mod.rs
- tests/linalg/udu.rs
Closes #762 
Concerns:
1. The structure is defined as `UDU<N: ComplexField, D: DimName>` instead of `UDU<N: ComplexField, D: Dim>`. That's because I could not find a way to initialize a zero matrix with `D: Dim`. How can I fix that?
2. The diagonal matrix is currently stored as `Matrix<N, D>` but it could easily be a `Vector<N, D>`. Is that preferable? It's an easy change.
3. On line 51 and 58 of src/linalg/udu.rs, the compiler did not accept an AddAssign operation, so I had to resort to an Add (e.g. `d[(j, j)] = d[(j, j)] + ...`). Is there a way I can specify in the `N` constraint that it needs to allow for AddAssign, and is that desired?
> Add UDU factorization

- .github/Xargo.toml
- .github/workflows/nalgebra-ci-build.yml
- Cargo.toml
- src/base/construction.rs
- src/base/helper.rs
- src/geometry/isometry_construction.rs
- src/geometry/orthographic.rs
- src/geometry/perspective.rs
- src/geometry/point_construction.rs
- src/geometry/quaternion_construction.rs
- src/geometry/rotation_specialization.rs
- src/geometry/similarity_construction.rs
- src/geometry/translation_construction.rs
- src/geometry/unit_complex_construction.rs
- src/lib.rs
- tests/lib.rs
This makes the `rand` dependency of `nalgebra` optional.
The `rand` crate may result in some difficulties when compiling `nalgebra` for `no-std` targets that are not supported by `getrandom`. So it is best to just make it optional so that people that don't need random don't have to take the extra steps to make their stack work.
This PR adds two new cargo features:
- `rand-no-std`: enables `rand` but not `rand/std`. This allows the use of `rand` on `no-std` environments supported by `getrandom`.
- `rand`: enables `rand/std`.
Fix #840
> Make the rand dependency optional.

- CHANGELOG.md
- src/base/matrix.rs
- src/geometry/dual_quaternion_construction.rs
- src/geometry/isometry_construction.rs
- src/geometry/point_construction.rs
- src/geometry/quaternion_construction.rs
- src/geometry/quaternion_conversion.rs
- src/geometry/rotation_construction.rs
- src/geometry/similarity_construction.rs
- src/geometry/translation_construction.rs
- src/geometry/unit_complex_construction.rs
This adds `cast` methods to most types. This can be used to change the type of the components of a given entity:
```rust
let vector = Vector3::new(1.0f64, 2.0, 3.0);
let vector_f32 = vector.cast::<f32>()`.
```
>  @sebcrozet Add "cast" methods to cast the type component types

- src/linalg/cholesky.rs
- tests/linalg/cholesky.rs
This adds a `.determinant()` method to `Cholesky`, which is computed as the square of the product of the diagonal elements in the Cholesky factor. The implementation is based on `LU`'s implementation of `.determinant()`, and the tests simply compare to the determinant computed by `LU`.
> Add determinant method to Cholesky

- .github/workflows/nalgebra-ci-build.yml
- Cargo.toml
This should make it possible to add the dev-dependency on criterion
without breaking `no_std` builds.
> Use the new Cargo resolver from Rust 1.50

- Cargo.toml
- src/geometry/quaternion_construction.rs
- src/linalg/symmetric_eigen.rs
- tests/lib.rs
The `nalgebra` tests are designed to require the "compare", "debug" and "rand" features. Due to this, running `cargo test` fails.
To hint users at this behavior, there is a custom compile error. However, this error is not shown in practice due to other compilation failures. This PR tries to rectify this by making some compilations conditional and using Cargo's `required-features` key.
> Better error message when running `cargo test`

- src/linalg/cholesky.rs
- tests/linalg/cholesky.rs
I realized that I forgot about complex element types when writing #860. I find it odd that the tests didn't catch this issue. Maybe `RandomSDP` happens to generate matrices such that the determinant of the Cholesky factor is always purely real, or maybe that's the case for all symmetric positive definite matrices?
The previous implementation was correct only for real elements. The Cholesky decomposition is `L L^H`, so the determinant is `det(L) * det(L^H)`. Since `L` is a triangular matrix, `det(L)` is the product of the diagonal elements of `L`. Since `L^H` is triangular and its diagonal elements are the conjugates of the diagonal elements of `L`, `det(L^H)` is the conjugate of `det(L)`. So, the overall determinant is the product of the diagonal elements of `L` times its conjugate.
> Fix Cholesky::determinant for complex elements

- src/base/construction.rs
- src/geometry/orthographic.rs
- src/geometry/perspective.rs
- src/geometry/point_construction.rs
- src/geometry/quaternion_construction.rs
- src/geometry/rotation_specialization.rs
- src/geometry/similarity_construction.rs
- src/geometry/translation_construction.rs
- src/geometry/unit_complex_construction.rs
- tests/core/helper.rs
This include the Rand-related changes from #622. It does not include any of the reworked Cargo features or removed `extern crate ...` statements from #622.
> More idiomatic use of Rand

- CHANGELOG.md
- src/base/conversion.rs
- src/geometry/isometry_conversion.rs
- src/geometry/point_construction.rs
- src/geometry/point_conversion.rs
- src/geometry/translation_conversion.rs
- src/third_party/glam/glam_isometry.rs
- src/third_party/glam/glam_translation.rs
- src/third_party/glam/mod.rs
- Conversion from an array `[T; D]` to an isometry `Isometry<T, _, D>` (as a translation).
- Conversion from a static vector `SVector<T; D>` to an isometry `Isometry<T, _, D>` (as a translation).
- Conversion from a point `Point<T; D>` to an isometry `Isometry<T, _, D>` (as a translation).
- Conversion of an array `[T; D]` from/to a translation `Translation<T, D>`.
- Conversion of a point `Point<T, D>` to a translation `Translation<T, D>`.
- Conversion of the tuple of glam types `(Vec3, Quat)` from/to an `Isometry2` or `Isometry3`.
- Conversion of a glam type `Vec2/3/4` from/to a `Translation2/3/4`.
> More conversions

- Cargo.toml
- nalgebra-sparse/Cargo.toml
Fixes some warnings produced by earlier versions since Rust 1.51.
See https://github.com/Andlon/matrixcompare/pull/5 for more details.
Note that we only update dev-dependencies, so there is no API breakage.
> Update matrixcompare version to 0.3.0

- src/base/conversion.rs
- tests/core/conversion.rs
Looks like the conversion between row-vectors and `[T; D]` disappeared unexpectedly in one of the recent `nalgebra` releases.
This PRs re-adds them.
> Re-add conversion between arrays and row vectors.

- src/base/vec_storage.rs
- tests/core/serde.rs
Fix #883 and adds tests that would have triggered unsoundness.
> Fix potential unsoundness after deserializing a DVector with a bad number or elements.

- nalgebra-sparse/src/coo.rs
PR for  #881
- Added doc tests as well. 
Note: I've noticed missing doc-tests in some of the APIs. Can add them in future PRs if it helps the documentation.
> CooMatrix::reserve added

- Cargo.toml
- src/base/array_storage.rs
- src/base/dimension.rs
- src/base/matrix.rs
- src/base/unit.rs
- src/geometry/isometry.rs
- src/geometry/quaternion.rs
- src/geometry/translation.rs
This should get nalgebra support started off. It's still missing support for all types as well as tests, but it does have distributive archived types so no logic needs to get rewritten.
> Add partial `rkyv` support

- nalgebra-sparse/src/csc.rs
CSC had the CSR docs for these methods
> Fix docs on csc_data(), csc_data_mut()

- nalgebra-macros/src/lib.rs
- nalgebra-macros/tests/tests.rs
- src/lib.rs
- tests/core/macros.rs
This new `point!` macro is similar to the `vector!` macro, except that it builds a point instead of a vector.
> Add a point! macro for constructing points

- Cargo.toml
- src/third_party/glam/common/glam_isometry.rs
- src/third_party/glam/common/glam_matrix.rs
- src/third_party/glam/common/glam_point.rs
- src/third_party/glam/common/glam_quaternion.rs
- src/third_party/glam/common/glam_rotation.rs
- src/third_party/glam/common/glam_similarity.rs
- src/third_party/glam/common/glam_translation.rs
- src/third_party/glam/common/glam_unit_complex.rs
- src/third_party/glam/mod.rs
- src/third_party/glam/v013/mod.rs
- src/third_party/glam/v014/mod.rs
- src/third_party/glam/v015/mod.rs
- src/third_party/mod.rs
This removes the `convert-glam` and `convert-glam-unchecked` features.
Instead, this adds the `convert-glam013`, `convert-glam014`, and `convert-glam015` features for conversions targeting the versions 0.13, 0.14, and 0.15 of `glam`.
With this change of features naming, we can provide conversions for multiple versions of glam, and a major version bump for glam will no longer require a major version bump for nalgebra.
The conversions behind the `convert-glam-unchecked` feature have been replaced by `TryFrom` impls or conversions that transform the input to generate a valid output.
> Support multiple version of the optional glam conversion

- nalgebra-sparse/src/coo.rs
- nalgebra-sparse/src/lib.rs
- nalgebra-sparse/tests/unit_tests/coo.rs
This MR adds a function which allow entire dense matrices to be pushed into a COO matrix. 
I wrote unit tests, but I haven't actually used it enough to recommend merging yet. I'm just hoping for any initial feedback.
> Add push_matrix fcn to COO

- src/linalg/pow.rs
All other methods in `nalgebra` that mutate an argument and may possibly fail, return a boolean. Furthermore, ever since writing the pow code I've learned that it's actually bad practice to use unit structs as error types. 
This change would be breaking.
> `Result<(), ()>` to `bool`

- src/base/array_storage.rs
- src/base/blas.rs
- src/base/default_allocator.rs
- src/base/edition.rs
- src/base/matrix_slice.rs
- src/base/ops.rs
- src/base/storage.rs
- src/base/vec_storage.rs
- src/linalg/inverse.rs
Fix #828 
- Add the safe methods: `ContiguousStorage::as_slice` and `ContiguousStorage::as_mut_slice`.
- The trait methods: `Storage::as_slice`, `StorageMut::as_mut_slice` have been renamed to `Storage::as_slice_unchecked` and `StorageMut::as_mut_slice_unchecked` and are marked as `unsafe`.
- The trait method `Storage::is_contiguous` is now marked as `unsafe`.
Not marking them as `unsafe` was invalid because they could result in invalid aliasing when calling `as_mut_slice` on two matrix slices obtained from the same matrix, but with overlapping (but non-contiguous) internal storage. For example, the following was allowed, but is actually unsound:
```rust
let (mut slice1, mut slice2) = matrix.rows_range_pair_mut(0, 1)
// Unsound because both mutable references point to the same element. …
```
> Fix potential undoundness with Storage::as_slice and StorageMut::as_mut_slice

- src/geometry/rotation.rs
...because it isn't unsafe, so clarify the documentation to match.
> Rotation::matrix_mut_unchecked may not cause UB

- nalgebra-glm/src/lib.rs
- nalgebra-lapack/src/lib.rs
- nalgebra-sparse/src/convert/mod.rs
- nalgebra-sparse/src/coo.rs
- nalgebra-sparse/src/csc.rs
- nalgebra-sparse/src/csr.rs
- nalgebra-sparse/src/lib.rs
- nalgebra-sparse/src/ops/mod.rs
- src/base/storage.rs
- src/lib.rs
- src/proptest/mod.rs
[The rustdoc book](https://doc.rust-lang.org/rustdoc/documentation-tests.html) states that all code between triple backticks is automatically interpreted as Rust code, and specifies the `ignore` keyword to not run a certain test. I removed all redundant instances of the `rust` keyword in code blocks, and replaced all instances of the undocumented keyword `.ignore` by their documented `ignore` counterpart.
> Trivial doc comment improvements

- src/geometry/point.rs
- src/geometry/point_construction.rs
This adds some missing fixes on top of the `point_dim_name` branch that were necessary for `serde` and `rand` integrations to work correctly.
Hopefully we can run the full CI suite to uncover additional problems.
> point_dim_name: Fix serde impls and Distribution impl for OPoint

- src/base/conversion.rs
- src/base/matrix_slice.rs
This PR adds an inherent `into_slice` and `into_slice_mut` method to `SliceStorage` and `SliceStorageMut` (the latter gets both). Also, to complement the `From` impls which convert slices to `DVectorSlice` and `DVectorSliceMut`, this PR adds corresponding `From` impls to convert back to the respective slice type.
The implementation is essentially a generalization of [`as_mut_slice_unchecked`](https://github.com/dimforge/nalgebra/blob/38add0b00df2bfba89b8e753e7cb16fcf4ae93c3/src/base/matrix_slice.rs#L190-L198). I just noticed https://github.com/dimforge/nalgebra/pull/905, I'm not sure how this relates to this new functions, but I guess they should be not affected because they consume the respective storage struct entirely.
This would implement #920
_From a consistency point of view, I …
> Allow to extract the inner slices of SliceStorage

- src/base/array_storage.rs
- src/base/matrix_slice.rs
- src/base/storage.rs
- src/base/vec_storage.rs
I removed some `unsafe` markers from methods that didn't need them, and added a bit of safety documentation to related methods.
> Removed unnecessary `unsafe` markers

- src/geometry/dual_quaternion.rs
- src/geometry/isometry.rs
- src/geometry/orthographic.rs
- src/geometry/perspective.rs
- src/geometry/reflection.rs
- src/geometry/rotation.rs
- src/geometry/similarity.rs
This was inconsistently applied, with some types having <T>, some having
<T: Scalar>, and some having <T: RealField>.
This unifies all types to match the convention of Matrix:
Just declare <T> at type def time, and apply bounds on impls only.
A significant advantage of this approach is const fn construction. Const
fn generics currently still can't have trait bounds, so any generic
const fn needs to only move opaque types around. Construction methods
such as new_unchecked or from_parts can be made const by removing their
generic bounds after this PR.
Actual constification is left to a follow-up PR.
Note that na::Transform is _not_ loosened here, as it has more complicated
definition requirements.
> Remove scalar bound from geometry type defs

- CHANGELOG.md
- src/geometry/point.rs
- src/geometry/point_alias.rs
- src/geometry/point_construction.rs
- src/geometry/point_conversion.rs
- src/geometry/point_coordinates.rs
- src/geometry/point_ops.rs
This PRs change the `Point` type so that its underlying implementation is based on type-level integers instead of const-generics. This introduces `OPoint` which takes type-level integers for its dimension, and `Point` is now a type-alias that takes const-generics for its dimension.
This changes is effectively a partial rollback of our migration to const-generics. This was requires because only allowing const-generics for point dimensions would code severe breakage on generic code using points. (And these breakage were unfixable because of the current limitations of const-generics.)
> Add a OPoint type that takes type-level integers instead of const-generics

- src/base/matrix.rs
- tests/core/matrix.rs
In the previous version, the test added in tests/core/matrix.rs failed to compile.
This version remove the dependency to the `Allocator<usize>`, so that the display implementation does not depend of the allocator of `nalgebra`, making it generical for `OMatrix`.
Not relying on `Omatrix<usize, R, C>` implies that some computation have to be done twice.
However, the performance hit is only in `Display`, which I find acceptable (the use case will be for debugging/writing logs)
The difference with the previous version is that `val_width` is called twice per entry instead of once.
> Make display generical for Omatrix

- src/lib.rs
This solves several issues encountered when trying to build with the alloc feature.
For one, the alloc feature is stable, and has been since Rust 1.36.0:
```rust
warning: the feature `alloc` has been stable since 1.36.0 and no longer requires
an attribute to enable
--> src/lib.rs:90:67
|
90 | #![cfg_attr(all(feature = "alloc", not(feature = "std")), feature(alloc))]
|                                                                   ^^^^^
|
= note: `#[warn(stable_features)]` on by default
warning: 1 warning emitted
```
Secondly, this breaks the build on stable:
```rust
~/g/r/cv   compilable  cv-optimize  cargo check
Checking nalgebra v0.27.1
error[E0554]: `#![feature]` may not be used on the stable release channel
--> /home/matthieu/.cargo/registry/src/github.com-1ecc6299db9ec823/nalge …
```
> import macros from alloc

- src/base/conversion.rs
I saw #216 and thought I'd just take five minutes and do it. I know it's kinda an old issue, so feel free to close this if the consensus there has changed.
Also, I saw that `AsRef`/`AsMut`/`Borrow`/`BorrowMut` isn't `impl`'d for `Quaternion` or `Complex` either. I could also go ahead and do those as well if no one can see a reason they shouldn't be.
> Implemented Borrow and BorrowMut on fixed size matrices

- src/geometry/point.rs
The bounds recently got a little too strict.
I probably messed this up when I fixed serde compilation during the recent `OPoint` introduction?
> Do not require T: (De)Serialize for OPoint impl

- Cargo.toml
Random support was gated by the "rand" feature in version 0.25.1, but not added to the docs.rs list, causing the gated functions to disappear from docs.
> Include "rand" in feature list for docs.rs

- src/geometry/orthographic.rs
- src/geometry/perspective.rs
- src/geometry/rotation.rs
Now that [`T` is unbounded](https://github.com/dimforge/nalgebra/pull/932), the unchecked constructors can be `const`.
> Make `from_matrix_unchecked`es const

- src/geometry/dual_quaternion.rs
- src/geometry/orthographic.rs
- src/geometry/perspective.rs
- src/geometry/rotation.rs
- src/geometry/transform.rs
- src/geometry/translation.rs
Adds impls for `bytemuck::Zeroable` and `bytemuck::Pod` to the `na::geometry::*` types that don't already have them. All added impls just fully gate themselves on the fields' impls for these traits, so they should all be sound, unless I missed one of the following conditions:
- The type has invalid values (semantically, in which case the traits shouldn't be impl'd); or
- The type is not stable layout (`#[repr(C)]` or `#[repr(transparent)]`; or
- The type is stable layout but may have padding (for _any_ value of `T` or other type parameters)
I believe this should reasonably close #830.
> Impl bytemuck traits for geometry types

- nalgebra-glm/src/aliases.rs
Currently, the doc comment for `Mat2x3` incorrectly describes it as a 2x2 matrix. Obviously this is a very minor issue, but I figured it was worth fixing.
> Fix a typo in the doc comment for `Mat2x3`

- src/base/statistics.rs
The `row_sum` documentation incorrectly referred to `row_variance_tr` instead of `row_sum_tr`.
> Fix wrong reference in docs

- src/geometry/rotation_construction.rs
- src/geometry/rotation_specialization.rs
The doc comments for `Rotation` incorrectly refer to quaternion instead of a rotation matrix. No code change, purely documentation.
> Improve clarity of Rotation doc comments

- src/linalg/cholesky.rs
- tests/linalg/cholesky.rs
Please see individual commits. This makes working with Cholesky quite a bit more flexible.
> Allow setting Cholesky field directly; more lax decomposition method

- nalgebra-glm/src/constructors.rs
Hello!
I have seen issue #984, noticed that it's a `good first issue`, decided to commit :)
What I did was simply swapping the two lines around.
EDIT
I have `grep`ed the whole rep and `mat3` doesn't seem to be called anywhere in the whole lib, so this change shouldn't break `nalgebra` itself
> Attempt to fix issue #984

- src/base/matrix.rs
- src/base/unit.rs
- src/geometry/point.rs
- src/geometry/quaternion.rs
- src/geometry/rotation.rs
- src/geometry/transform.rs
- src/geometry/translation.rs
- tests/core/matrix.rs
Replace the verbose derived (or nearly equivalent) `Debug` impls for several newtypes with explicit impls that forward to the inner type, making readable diagnostics logging much easier.
I've found absolutely every time I'm trying to debug-log a nalgebra type I need to manually dig out the underlying array to have any hope of being able to scan a large amount of logged data to find irregularities. This is particularly awkward when I'm trying to log a structure that contains various nalgebra types, and hence can't just have `.coords.data` or whatever slapped on the end. This is also consistent with the existing `Debug` impls for e.g. `Orthographic3` and `Perspective3`, and with e.g. `Vec` in the stdlib.
In most cases, formatting is directly forwarded to the contents of each newtype. When a …
> Concise Debug impls

- src/base/properties.rs
- src/geometry/dual_quaternion.rs
- src/geometry/isometry.rs
- src/geometry/similarity.rs
- src/geometry/unit_complex.rs
This benchmark shows ~4% performance improvement.
```rust
use nalgebra as na;
use rand::prelude::*;
use std::time::{Duration, Instant};
fn main() {
let mut time = Duration::ZERO;
const N: usize = 500_000;
for _ in 0..N {
time += bench();
}
dbg!(time);
}
fn bench() -> Duration {
let mut rng = thread_rng();
let m1 = na::DMatrix::<f32>::new_random(rng.gen_range(10..100), rng.gen_range(10..100));
let timer = Instant::now();
let _ = m1.is_identity(1.0);
timer.elapsed()
}
```
> Simplify Matrix::is_identity while also improving performance

- src/linalg/decomposition.rs
- src/linalg/svd.rs
- tests/linalg/svd.rs
Calculating an SVD with descending singular values is commonly required for different applications in machine learning and computer vision (#349, #897). This pull request adds a function `sort_by_singular_values` and corresponding tests to enforce such an ordering for these use cases. As this sorting is completely optional, the users must "pay" for this specific order only if it is really required.
> Allow descending sorting of estimated SVD

- nalgebra-lapack/src/lib.rs
- nalgebra-lapack/tests/lib.rs
Without these declarations, `nalgebra-lapack` does not have runtime
linkage requirements for these libraries, meaning that binaries and
libraries using `nalgebra-lapack` have to link `lapack`/`lapack-src`
explicitly which shouldn't be necessary.
> Add extern crate declarations for lapack{-src}

- src/geometry/dual_quaternion.rs
- tests/geometry/dual_quaternion.rs
Solves #1013.
Previously, when screw-linearly interpolating two unit dual quaternions
that had an identical orientation, `try_sclerp` would return `None`, as
the operation would introduce a division-by-zero.
This PR splits out the cases where two unit dual quaternions have an
identical orientation from the cases where they have opposite
orientations. In the case where they have identical orientations, the
operation is well-defined, but the exponential parameterization could
not handle it without introducing NaNs. Therefore, the function detects
this case and simply defaults to linearly interpolating the
translational components and using one of the two inputs' rotation
components.
The case where the inputs have opposite rotations is now detected
separately using the dot product of the …
> Don't panic ScLERPing `UnitDualQuaternion` with equal rotation

- .github/workflows/nalgebra-ci-build.yml
- CHANGELOG.md
- Cargo.toml
- nalgebra-glm/Cargo.toml
- src/base/array_storage.rs
- src/base/dimension.rs
- src/base/indexing.rs
- src/base/matrix.rs
- src/base/unit.rs
- src/geometry/dual_quaternion.rs
- src/geometry/isometry.rs
- src/geometry/orthographic.rs
- src/geometry/perspective.rs
- src/geometry/point.rs
- src/geometry/quaternion.rs
- src/geometry/rotation.rs
- src/geometry/scale.rs
- src/geometry/similarity.rs
- src/geometry/transform.rs
- src/geometry/translation.rs
The ` rust-CUDA` project has been announced yesterday (see the [reddit announcement](https://www.reddit.com/r/rust/comments/qzv428/announcing_the_rust_cuda_project_an_ecosystem_of/)). It makes it extremely easy to write CUDA kernels using `no-std` rust code. It is extremely likely to become the go-to CUDA solution, and I would like to support this effort to improve the GPU-computing situation in Rust.
This PR makes all the `no-std` types from `nalgebra` compatible with `rust-CUDA` (which means that `nalgebra` structs can be copied from/to the GPU device using `cust`).
Another PR will have to be made on `simba` in order to ensure that `nalgebra` uses the proper `cuda` intrinsics when targetting the GPU.
I am not sure if it will be possible to add a compuration targetting `cuda` succeed on …
> Add support for rust-CUDA

- src/base/unit.rs
- src/geometry/quaternion.rs
- src/geometry/unit_complex.rs
It is still unclear whether or not the support of `Complex` by `Rust-CUDA` will be added as part of the [cust crate](https://github.com/Rust-GPU/Rust-CUDA/pull/10) or as part of the [num-complex crate](https://github.com/rust-num/num-complex/issues/97). In the mean time, this PR manually implements `DeviceCopy` for `UnitComplex` (and other unit types) instead of using `impl DeviceCopy for Unit<T>`.
> Implement DeviceCopy for UnitComplex, UnitQuaternion, and Unit<Matrix> instead of using a blanket impl

- benches/linalg/svd.rs
- src/linalg/mod.rs
- src/linalg/qr.rs
- src/linalg/svd.rs
- src/linalg/svd2.rs
- src/linalg/svd3.rs
- tests/linalg/svd.rs
This implements special-cases for the 2x2 and 3x3 SVDs for real matrices.
The 2x2 implementation uses an analytical solution and is about 75% faster than the generic implementation.
The 3x3 implementation uses an eigendecomposition followed by a QR decomposition. The performance gain is marginal on the CPU (about 10%) but seems more significant on the GPU/CUDA when tested on actual data (probably because less branching are involved for the symmetric eigendecomposition than for the SVD).
> Add dedicated implementations of SVD for 2x2 and 3x3 real matrices.

- .github/workflows/nalgebra-ci-build.yml
- src/linalg/svd.rs
- src/linalg/svd2.rs
- src/linalg/svd3.rs
- tests/lib.rs
- tests/linalg/svd.rs
I stumbled upon a matrix that failed the special-case for 3x3 SVD on real matrices that I introduced in #1034.
It turns out that I skipped an important step: sorting the singular values before running the QR decomposition.
In this PR, I:
- add a sorting step in the the 3x3 SVD. This doesn’t appear to change the performances on either CPU or GPU.
- add a test to skip the `sort_by_singular_values` called by `matrix.svd()` on 2x2 and 3x3 real matrices (because the special SVD implementation always sort the singular values anyway).
- add to most of our SVD tests an assertion  checking that the singular values are actually sorted.
- add the problematic 3x3 matrix I found to the tests.
I’m actually surprised that our proptest tests didn’t catch this edge-case earlier (we even already had a …
> Fix the special-case for 3x3 Real SVD

- nalgebra-sparse/Cargo.toml
- nalgebra-sparse/src/io/matrix_market.pest
- nalgebra-sparse/src/io/matrix_market.rs
- nalgebra-sparse/src/io/mod.rs
- nalgebra-sparse/src/lib.rs
- nalgebra-sparse/tests/unit.rs
- nalgebra-sparse/tests/unit_tests/matrix_market.rs
- nalgebra-sparse/tests/unit_tests/mod.rs
Hi, 
I have just implemented some part of io code about sparse matrix. Right now, it can read a matrix market data into a `nalgebra_sparse::CooMatrix` with error handling. It can be enabled by `--features io`. And also it contains several correct examples in unit test, which can be run by `cargo test --features proptest-support --features compare --features io test_mm`, also it contains several wrong examples in doc test, in `nalgebra_sparse::io::MMErrorKind`, which can be run by `cargo test --doc --features io MMErrorKind`
> added reading matrix market data to sparse coomatrix

- src/base/edition.rs
- src/base/matrix.rs
Original issue:  #1046.
Should I add  "Triangular matrix extraction" bullet to Matrix documentation, now as it is decoupled from select functions?
> Relax T: Zero bound on Matrix::select_rows() and Matrix::select_columns()

- src/linalg/decomposition.rs
- src/linalg/svd.rs
- tests/linalg/svd.rs
Code inspired by this PR/thread: https://github.com/dimforge/nalgebra/pull/656
Main person behind this is @LucasCampos
This PR  implements  [matrix polar decomposition](https://en.wikipedia.org/wiki/Polar_decomposition)
> Take-2 of polar-decomposition

- src/linalg/pow.rs
- tests/linalg/mod.rs
- tests/linalg/pow.rs
This PR fixes `Matrix::pow` and makes it work with integer matrices. The exponent can no longer be negative (to compute a negative exponent, simply invert the matrix before calling `pow`).
Proptest-based tests have been added for `Matrix::pow`.
Fix #1021, fix #1042
> Fix Matrix::pow and make it work with integer matrices

- nalgebra-macros/src/lib.rs
- src/base/blas.rs
- src/base/matrix.rs
- src/geometry/dual_quaternion.rs
- src/geometry/dual_quaternion_construction.rs
- src/geometry/orthographic.rs
- src/geometry/point.rs
- src/geometry/quaternion.rs
- src/geometry/similarity_construction.rs
- src/geometry/translation.rs
- src/lib.rs
Close example code fences and normalize containing head line in touched files.
Remove stale reference to `slice_assume_init` (commit 8c6ebf27), fix long dead internal links in deprecation notices.
> Cleanup examples and doc links

- src/base/dimension.rs
> Simplify the type definitions of Const aliases, to help rust-analyzer

- src/geometry/unit_complex.rs
- tests/geometry/rotation.rs
> fix for `UnitComplex::slerp()` #1093

- Cargo.toml
- src/base/array_storage.rs
- src/base/dimension.rs
- src/base/matrix.rs
- src/base/unit.rs
- src/geometry/dual_quaternion.rs
- src/geometry/isometry.rs
- src/geometry/orthographic.rs
- src/geometry/perspective.rs
- src/geometry/point.rs
- src/geometry/quaternion.rs
- src/geometry/rotation.rs
- src/geometry/scale.rs
- src/geometry/similarity.rs
- src/geometry/translation.rs
- src/lib.rs
upgrade rkyv to 0.7
update resolve functions
add bytecheck impls if not #[no-std]
> improve rkyv support

- Cargo.toml
- src/third_party/glam/common/glam_matrix.rs
- src/third_party/glam/common/glam_point.rs
- src/third_party/glam/mod.rs
- src/third_party/glam/v021/mod.rs
Add feature `convert-glam021`.
Conversion macros changed to use the `From` trait to convert glam types to arrays because The `BVec*` types no longer implement `AsRef`.
> Support conversion for glam `0.21`.

- src/geometry/quaternion_construction.rs
- src/geometry/rotation_specialization.rs
- tests/geometry/rotation.rs
One possibility of fixing issues #627, #1078 by starting from a random rotation.
I'm not too familiar with how this whole Standard: Distribution<Rotation3<T>> works, so feel free to change to something better.
Of course, one downside of this approach is that in the very rare case of running into the bug (if one gets really unlucky), it might disappear when you re-run it.
Hence, another option would be (if one does not always want to start from a new random rotation) to fix the "random" rotation.
An idea could also be to only do this extra check if the output happens to match the first guess (up to ε), and then start from the next "deterministic" random rotation.
Alternatively, one could check if the determinant of the provided matrix is 1, and then use from_matrix_unchecked, however, this …
> Fix from_matrix when argument is already a valid rotation matrix

- src/geometry/unit_complex_construction.rs
I have a test failing on macOS (MacBook Pro M1 Max) on dev that isn't failing in CI. It looks like a precision issue as a result of the equality assertion only running in CI or x86.
```
failures:
---- src/geometry/unit_complex_construction.rs - geometry::unit_complex_construction::UnitComplex<T>::cast (line 133) stdout ----
Test executable failed (exit code 101).
stderr:
thread 'main' panicked at 'assertion failed: `(left == right)`
left: `Complex { re: 0.5403023, im: 0.84147096 }`,
right: `Complex { re: 0.54030234, im: 0.841471 }`', src/geometry/unit_complex_construction.rs:7:1
stack backtrace:
0:        0x102df1310 - std::backtrace_rs::backtrace::libunwind::trace::h449592924b3bd63f
at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind. …
```
> Fix UnitComplex cast doctest failure on macOS

- src/base/default_allocator.rs
Minor modification to docs, since IIUC `GenericArray` is no longer used by nalgebra.
> Update DefaultAllocator docs to say ArrayStorage instead of GenericArray

- src/base/dimension.rs
fixes #1139
My dev environment is not set up properly for nalgebra, so I've been unable to test this locally in any of the standard ways, but these changes work correctly with Hypermine, and the changes are simple enough that I believe it's worth creating a PR anyway.
Please let me know if there's anything I need to do before this can be merged, if it can be merged at all.
> Use #[inline] to improve opt-level 1 performance

- src/base/matrix.rs
Currently, `cast` is resolved via `Unit`'s `Deref` impl, which leads to it confusingly stripping the `Unit` from `UnitVector`s. Add an inherent impl which takes precedence, similar to the existing specialization for `UnitQuaternion`.
Wasn't entirely sure where to put the definition, hope it makes sense where it is.
> Implement `cast` for `Unit<Vector<T, D, S>>`

- nalgebra-sparse/src/coo.rs
- nalgebra-sparse/tests/unit_tests/coo.rs
This PR adds the `clear_triplet()` method to the `CooMatrix` struct.
The goal of the method is to be able to remove triplets before construction.
Some outstanding questions:
* Spelling of the method? @Andlon suggested `clear_triplet` in the Discord. Another option might be `pop` or `pop_triplet` to correspond to `push`.
* Should out of bounds values cause a panic? It is probably fine to just return a `None` value.
* What should the return type be? Currently it is `Option<T>`.
> [Sparse] Add `clear_triplets()`

- src/lib.rs
Helpful because lib.rs is the 'main page' for docs.rs
This allows for easy/direct access to the mentioned types
Currently you need to look up mentioned types via the search bar
> Link listed types in lib.rs to their docs

- CHANGELOG.md
- Cargo.toml
- Use `#[inline]` on the `Dim` implementation for `Const` to improve opt-level 1 performance.
- Make the `Point::new` constructions const-fn.
- Add `UnitVector::cast` to change the underlying scalar type.
> Release v0.31.2

- nalgebra-sparse/src/coo.rs
- nalgebra-sparse/tests/unit_tests/coo.rs
There are certain cases where one might want to modify the values stored in the triplets in a COO matrix before constructing a `Csr` or `Csc` matrix.
Currently the way to do this would either be by decomposing the `CooMatrix`
```rust
let mut coo = /* ... */;
let nrows = coo.nrows();
let ncols = coo.ncols();
let (rows, cols, mut values) = coo.disassemble();
values.iter_mut().for_each(|v| /* ... */);
CooMatrix:: try_from_triplets(nrows, ncols, rows, cols, values).unwrap();
```
Or clearing the triplets and inserting new values
```rust
let mut coo = /* ... */;
let new_triplets = coo.triplet_iter().map(|(i, j, &v)|  (i, j, /* mutate v */));
coo.clear_triplets();
for (i, j, v) in new_triplets {
coo.push(i,j,v);
}
```
> [Sparse] Add `triplet_iter_mut()`

- .github/workflows/nalgebra-ci-build.yml
- Cargo.toml
- src/base/array_storage.rs
- src/base/dimension.rs
- src/base/matrix.rs
- src/base/unit.rs
- src/geometry/dual_quaternion.rs
- src/geometry/isometry.rs
- src/geometry/orthographic.rs
- src/geometry/perspective.rs
- src/geometry/point.rs
- src/geometry/quaternion.rs
- src/geometry/rotation.rs
- src/geometry/scale.rs
- src/geometry/similarity.rs
- src/geometry/translation.rs
- tests/core/mod.rs
- tests/core/rkyv.rs
According to the [rkyv book](https://rkyv.org/validation.html), the `CheckBytes` trait derive should be applied inside `archive_attr` attribute, or we cannot deserialize data without `unsafe` code.
This PR also added some trivial tests for rkyv serialization and deserialization.
> Fix usage of CheckBytes

- nalgebra-sparse/src/csc.rs
- nalgebra-sparse/src/csr.rs
Currently the CSR matrix example isn't self contained, because `coo` isn't defined in the code. This PR fixes that by defining a `coo` matrix, so users reading the example can copy/paste the code for a working example.
> Make CSR matrix example more self contained

- src/base/matrix.rs
Just like the `cast()` method in `Matrix` is the equivalent of `convert()` with more concise syntax, it would be convenient to have a method that enables the less restrictive conversions of `try_convert()` in the same way.
> Added `try_cast()` to `Matrix`.

- src/geometry/quaternion.rs
- src/geometry/rotation_specialization.rs
- src/geometry/unit_complex.rs
Changes `]0, pi]` to `(0, pi]`.
Replaces PR #1173 and resolves Issue #1164.
> Use parenthesis for exclusive lower bound

- .github/workflows/nalgebra-ci-build.yml
This adds a simple `cargo doc` step to CI for the repo.
Pending discussion of more complex options for `cargo doc`, this should address #1151.
> Add simple cargo doc step to CI

- Cargo.toml
- src/base/array_storage.rs
- src/base/dimension.rs
- src/base/matrix.rs
- src/base/unit.rs
- src/geometry/dual_quaternion.rs
- src/geometry/isometry.rs
- src/geometry/orthographic.rs
- src/geometry/perspective.rs
- src/geometry/point.rs
- src/geometry/quaternion.rs
- src/geometry/rotation.rs
- src/geometry/scale.rs
- src/geometry/similarity.rs
- src/geometry/translation.rs
- src/lib.rs
- tests/core/mod.rs
- tests/core/rkyv.rs
make it so that nalgebra objects archive as themselves. Allows for implementations on `Matrix` and other types to also work in a zero-copy environment.
Draft PR, I will extend this to the other types soon. Any critiques or help with figuring out why I can't `allow(unused_qualifications)` in `cfg_attr` are welcome.
> allow for nalgebra objects to be their own rkyv::Archive

- src/linalg/cholesky.rs
This PR implements a function that returns natural logarithm of determinant similar to the one in [NumPy](https://numpy.org/doc/stable/reference/generated/numpy.linalg.slogdet.html) and in [ndarray-linalg](https://docs.rs/ndarray-linalg/latest/ndarray_linalg/cholesky/trait.DeterminantC.html#tymethod.ln_detc).
> Add ln_determinant to Cholesky

- .github/workflows/nalgebra-ci-build.yml
- Cargo.toml
- src/base/iter.rs
- src/base/matrix.rs
- src/base/mod.rs
- src/base/par_iter.rs
- tests/core/matrix.rs
- tests/lib.rs
**Short**: Enable parallel column iterators for matrices with rayon
**Fixes**: #848 
**Changes**:
* Added functions `par_column_iter` and `par_column_iter_mut` to enable iteration over (mutable) columns in parallel
* The serial `ColumnIterMut` is now Send. I changed a few things that I am not sure make the code any more or less safe than before. I'm grateful for a review.
* Both `ColumnIter` and `ColumnIterMut` are now double ended (rayon needs this). This required me to stick another pointer sized integer in there, increasing the size of an iterator by 50%. (from 2 pointer sized members to 3)
* Added tests covering serial and parallel iterators
**Notes**:
* I will want to feature gate this functionality on crate feature `rayon` or `parallel`. I'll do that when I get greenlight on the …
> Parallel Column Iterators with Rayon

- src/linalg/convolution.rs
This fixes the CI breaking because nightly now correctly detects these unnecessary parentheses.
> Fix CI by removing unnecessary parentheses

- src/base/array_storage.rs
Breaking change. Consistent with how serde serializes plain arrays. Saves a length tag in common serialization formats (e.g. bincode, punchcard).
> Serialize statically sized matrices as tuples

- nalgebra-macros/src/lib.rs
- nalgebra-macros/tests/tests.rs
When splitting e.g. fields over multiple lines it is quite common to add a
trailing comma in the last line in rust code.
This pr makes it so that this is allowed now:
```rust
vector![
some_longer_expression() + something,
some_longer_expression() + something_else,
some_longer_expression() + another_thing,
some_longer_expression() + 42,
];
```
I also added a test verifying that this was already the case with `matrix!`.
> Allow trailing punctuation in macros

- src/base/matrix.rs
I believe that the Matrix PartialEq implementation does not require that T implements Scalar.
Removing this bound would allow for users to derive PartialEq on custom generic structures without requiring that T: Scalar. For example
```rust
#[derive(PartialEq)]
struct MyCoolStructure<T>{
m: Vector2<T>
}
```
> fix: remove Scalar trait bound for Matrix PartialEq and Eq

- src/base/matrix.rs
Allows for converting a `Matrix1` to a scalar without having to index.
The test is implemented as a doctest, since I couldn't find anything else that would check whether or not code compiles.
Under the hood, it still just indexes, but the method is only available on `Matrix1`.
One question is whether or not this should return a borrowed value or an owned value. I assume borrowed, but for most cases it would likely be immediately dereferenced.
Closes #1209
> Add `.item()` to `Matrix1`

- src/geometry/rotation_specialization.rs
At the moment, Rotation only has a way to get Euler angles in the order roll, pitch, yaw. This PR adds a euler_angles_ordered function to Rotation which allows the user to specify any order of Euler axes. It also allows the user to specify if the returned angles should be for an intrinsic or extrinsic rotation.
The implementation is based upon this paper:
Malcolm D. Shuster, F. Landis Markley, “General formula for extraction the Euler angles”, Journal of guidance, control, and dynamics, vol. 29.1, pp. 215-221. 2006
This is a function I wrote in one of my own projects, and thought it would be a good addition to the library.
> Add euler_angles_ordered function on Rotation

- src/geometry/rotation_specialization.rs
`zaxis` and `xaxis` are already normalized which means `zaxis.cross(&xaxis)` should already be normalized.
> Remove unnecessary normalization in `Rotation3::face_towards`

- src/base/iter.rs
Could be needed for crates like https://docs.rs/logaddexp/latest/logaddexp/.
Other iterators in nalgebra also have `Clone` impl.
> Add `Clone` to `MatrixIter` and `MatrixIterMut`

- Cargo.toml
- src/base/array_storage.rs
- src/base/dimension.rs
- src/base/matrix.rs
- src/base/unit.rs
- src/geometry/dual_quaternion.rs
- src/geometry/isometry.rs
- src/geometry/orthographic.rs
- src/geometry/perspective.rs
- src/geometry/point.rs
- src/geometry/quaternion.rs
- src/geometry/rotation.rs
- src/geometry/scale.rs
- src/geometry/similarity.rs
- src/geometry/translation.rs
The explicit `bytecheck` dependency is unnecessary as we can access it through `rkyv` directly. This makes keeping dependency version in sync easier.
This replaces #1258.
> chore: remove explicit bytecheck dependency

- src/base/alias_view.rs
* Indicate whether they are immutable/mutable clearly.
* Link to the other form (immutable link to mutable, mutable to immutable).
* Consistently include the text about it being an alias and to look elsewhere for the methods.
> docs: Improve view alias docs.

- src/base/constraint.rs
(Also pick up a small typo in a non-doc comment in the same area of code.)
> docs: grammar: "Constrains ... to be"

- src/lib.rs
This change fixes the following compiler warnings that occur with the very first demo in lib.rs:
```
warning: unused return value of `Relative::<A, B>::eq` that must be used
--> src/main.rs:11:5
|
11 |     relative_eq!(b.axis().unwrap(), axis);
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_must_use)]` on by default
= note: this warning originates in the macro `relative_eq` (in Nightly builds, run with -Z macro-backtrace for more info)
warning: unused return value of `Relative::<A, B>::eq` that must be used
--> src/main.rs:12:5
|
12 |     relative_eq!(b.angle(), angle);
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: this warning originates in the macro `relative_eq` (in Nightly builds, run with -Z macro-backtrace for more info)
warning: `nalgebra-experiments` (bin …
```
> DOC: Fix compiler warning in the first example in lib.rs.

- src/base/iter.rs
This fixes an unused code warning. Since the code is `pub(crate)`, it was only available within the crate and only used by Rayon code, so it is no functional change to not compile it except when the right feature is enabled.
Also, fix a minor typo in some non-doc comments.
> `split_at` is only used by Rayon code.

- src/geometry/quaternion.rs
This looks like copy-pasted from `magnitude_squared()`.
> DOC: Use norm_squared() in its doctest

- nalgebra-sparse/src/coo.rs
- nalgebra-sparse/tests/unit_tests/coo.rs
Calls `try_from_triplets` for now, and is mentioned in the documentation.
Closes #1286
> Add `try_from_triplets_iter`

- nalgebra-glm/src/constructors.rs
Matrix constructors need more args.
> nalgebra-glm, clippy: Suppress too_many_arguments.

- src/geometry/dual_quaternion.rs
By taking a ref, we can avoid an extra copy on the caller side.
> DualQuaternion: Fix to_vector self convention.

- nalgebra-glm/src/common.rs
- nalgebra-glm/src/ext/matrix_projection.rs
- nalgebra-glm/src/gtc/constants.rs
- nalgebra-glm/src/trigonometric.rs
These imports are redundant and not needed.
> nalgebra-glm: Fix clippy single_component_path_imports.

- benches/core/matrix.rs
- benches/lib.rs
This also removes the `#![feature(bench_black_box)]`. This was stabilized in Rust 1.66 and anyone building benchmarks will be on that or later (as they previously would have been on nightly).
This also allows building `cargo build --all-targets` on stable Rust as it no longer dies when hitting the feature addition in the benchmarks.
> Use std::hint::black_box consistently.

- src/geometry/isometry_construction.rs
> doc: Isometry's `look_at_lh` is left-handed.

- nalgebra-glm/src/aliases.rs
- nalgebra-glm/src/common.rs
- nalgebra-glm/src/exponential.rs
- nalgebra-glm/src/ext/matrix_projection.rs
- nalgebra-glm/src/ext/matrix_transform.rs
- nalgebra-glm/src/ext/scalar_common.rs
- nalgebra-glm/src/ext/scalar_constants.rs
- nalgebra-glm/src/ext/vector_common.rs
- nalgebra-glm/src/ext/vector_relational.rs
- nalgebra-glm/src/geometric.rs
- nalgebra-glm/src/gtc/constants.rs
- nalgebra-glm/src/gtc/matrix_access.rs
- nalgebra-glm/src/gtc/type_ptr.rs
- nalgebra-glm/src/gtx/component_wise.rs
- nalgebra-glm/src/gtx/handed_coordinate_space.rs
- nalgebra-glm/src/gtx/matrix_cross_product.rs
- nalgebra-glm/src/gtx/matrix_operation.rs
- nalgebra-glm/src/gtx/norm.rs
- nalgebra-glm/src/gtx/normalize_dot.rs
- nalgebra-glm/src/gtx/transform.rs
- nalgebra-glm/src/gtx/transform2d.rs
- nalgebra-glm/src/gtx/vector_query.rs
- nalgebra-glm/src/lib.rs
- nalgebra-glm/src/vector_relational.rs
- nalgebra-sparse/src/csc.rs
- nalgebra-sparse/src/csr.rs
- nalgebra-sparse/src/lib.rs
- src/lib.rs
- src/proptest/mod.rs
This fixes almost all HTML links to be intradoc links that Rust can verify during `cargo doc`. This will help prevent future broken links.
> docs: Use intradoc links rather than HTML.

- src/linalg/bidiagonal.rs
- src/linalg/givens.rs
- tests/linalg/bidiagonal.rs
- tests/linalg/svd.rs
This resolves issue #1313.
The problem was in the bidiagonalization where U and V is computed. There is a corner case where U D V doesn't agree how the sign should be handled when the reflection axis has zero magnitude.
This solution fixes the correctness but I would like some input on how to make the test for zero magnitude more efficient.
> Fix bug in SVD related to values near zero

- nalgebra-sparse/src/cs.rs
- nalgebra-sparse/src/csc.rs
- nalgebra-sparse/src/csr.rs
- nalgebra-sparse/src/pattern.rs
- nalgebra-sparse/tests/unit_tests/csc.rs
- nalgebra-sparse/tests/unit_tests/csr.rs
- nalgebra-sparse/tests/unit_tests/pattern.rs
- src/base/vec_storage.rs
This solves https://github.com/dimforge/nalgebra/issues/1204 and implements the `Default` trait for `CsMatrix`, `CscMatrix`, `CsrMatrix`, `SparsityPattern`, and `VecStorage`, applying the changes proposed by @Andlon in https://github.com/dimforge/nalgebra/pull/1206.
I added some unit tests where applicable as well.
> Implement Default trait for sparse matrix types

- src/base/conversion.rs
- src/base/iter.rs
- tests/core/matrix.rs
Fixes #747 
First of all - thanks for this crate, it's really fun to use, except for the lack of `IntoIterator` impls on (owned) view storages.
This allows overcoming the borrow checker issues when trying to do something like this:
Using the `IntoIterator` impl from this PR:
I implemented this feature by extracting a common subset of `MatrixIter` and `MatrixIterMut` into a `RawIter` struct which erases the lifetime it is created with, and iterates over raw pointers instead of references.
Then, the `MatrixIter(Mut)` structs become simple wrappers over `RawIter`, but with an added lifetime constraint.
It's technically possible to keep the old code (and remove most of the code added in this PR) and impl the new `new_owned` and `new_owned_mut` using a transmute from `MatrixIter<'outer, ...>` …
> Allow creating matrix iter with an owned view

- Cargo.toml
Fixes #623 (specifically about `Complex::from_polar` at least)
`nalgebra`'s `std` cargo feature now also enables the `std` feature of some dependencies that use `default-features = false` (`num-traits`, `num-rational`, `num-complex`, `approx`, (if enabled) `alga`)
(Note: the  `"alga?/std"` syntax for enabling features of optional dependencies without necessarily enabling the optional dependency itself was only stabilized in Rust 1.60, but `nalgebra` seems to state that it's MSRV policy is ["latest stable"](https://docs.rs/nalgebra/latest/nalgebra/#using-nalgebra) so that would be fine.)
> Forward `std` feature to some deps.

- src/geometry/point.rs
- tests/geometry/point.rs
Invokes `T::fmt` rather than `write!`, which allows points to be formatted with modifiers like so:
```rust
let p = Point3::new(1.23, 3.45, 5.67);
assert_eq!(&format!("{p}"), "{1.23, 3.45, 5.67}");
assert_eq!(&format!("{p:.1}"), "{1.2, 3.5, 5.7}");
assert_eq!(&format!("{p:.0}"), "{1, 3, 6}");
```
I was not sure where to place the simple test code, it is currently adjacent in the file.
> Make OPoint call `T::fmt` to respect formatting modifiers

- .github/workflows/nalgebra-ci-build.yml
- CHANGELOG.md
- Cargo.toml
- nalgebra-glm/Cargo.toml
- src/base/array_storage.rs
- src/base/dimension.rs
- src/base/matrix.rs
- src/base/unit.rs
- src/geometry/dual_quaternion.rs
- src/geometry/isometry.rs
- src/geometry/orthographic.rs
- src/geometry/perspective.rs
- src/geometry/point.rs
- src/geometry/point_construction.rs
- src/geometry/quaternion.rs
- src/geometry/rotation.rs
- src/geometry/scale.rs
- src/geometry/similarity.rs
- src/geometry/transform.rs
- src/geometry/translation.rs
- src/geometry/unit_complex.rs
Fixes https://github.com/dimforge/nalgebra/issues/1330. Required to get CI green again. This is a breaking change.
> Remove CUDA support relying on abandoned toolchain

- CHANGELOG.md
- Cargo.toml
- src/third_party/glam/mod.rs
- src/third_party/glam/v025/mod.rs
Glam was updated to 0.25 a few weeks ago, so this PR adds type conversion for it through the `glam-0.25` feature. This will be needed for migrating e.g. Bevy physics engines to Bevy 0.13 once it is released.
Let me know if I missed something I need to update!
> Support Glam 0.25 type conversion

- nalgebra-glm/src/gtx/vector_query.rs
The existing comparison bound of $\epsilon^2$ is improperly scaled for testing an epsilon of the squared vector magnitude. Let $\epsilon$ be our specified epsilon and $\delta$ be the permissible delta of the squared magnitude. Thus, for a nearly-normalized vector, we have
$$\begin{align}
\sqrt{1 + \delta} &=  1 + \epsilon        \\
\delta  &= (1 + \epsilon)^2 - 1 \\
\delta  &=  \epsilon^2 + 2\epsilon
\text{ .}\end{align}$$
Since we only care about small epsilon, we can assume that $\epsilon^2$ is small and just use $\delta = 2\epsilon$. And in fact, [this is the bound used by GLM][GLM#isNormalized] (MIT license) ... except they're using `length` and not `length2` for some reason.
[GLM#isNormalized]: https://github.com/g-truc/glm/blob/b06b775c1c80af51a1183c0e167f9de3b2351a79/glm/gtx/vector_ …
> Fix `glm::is_normalized` epsilon test

- src/linalg/symmetric_eigen.rs
On the latest release of rustc on the beta channel, running `cargo test` fails:
```
error[E0283]: type annotations needed for `matrix::Matrix<T, base::dimension::Const<2>, base::dimension::Const<2>, array_storage::ArrayStorage<T, 2, 2>>`
--> src/linalg/symmetric_eigen.rs:363:17
|
363 |             let m = Matrix2::new_random();
|                 ^   --------------------- type must be known at this point
|
= note: cannot satisfy `_: base::scalar::Scalar`
note: required by a bound in `construction::<impl matrix::Matrix<T, R, C, <default_allocator::DefaultAllocator as base::allocator::Allocator<T, R, C>>::Buffer>>::new_random`
--> src/base/construction.rs:647:9
|
639 |         pub fn new_random($($args: usize),*) -> Self
|                ---------- required by a bound in this associated …
```
> Fix type inference error in tests on rustc beta

- src/base/storage.rs
According to Miri, `RawStorageMut::swap_unchecked_linear` introduces a stacked borrows violation:
```text
➜  nalgebra git:(dev) ✗ cargo miri test -- edition::swap
Preparing a sysroot for Miri (target: x86_64-unknown-linux-gnu)... done
Compiling nalgebra-macros v0.2.1 (/home/yotam/nalgebra/nalgebra-macros)
Compiling nalgebra v0.32.3 (/home/yotam/nalgebra)
Running tests/lib.rs (target/miri/x86_64-unknown-linux-gnu/debug/deps/lib-85cd9506b7860f9a)
running 2 tests
test core::edition::swap_columns ... error: Undefined Behavior: attempting a read access using <268833> at alloc82401[0x18], but that tag does not exist in the borrow stack for this location
--> /home/yotam/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:878:9
|
878  | …
```
> Fix UB in `RawStorageMut::swap_unchecked_linear`

- src/linalg/householder.rs
- tests/linalg/eigen.rs
The column may not be normalized if the `factor` is on a scale of 1e-40.
Possibly, `f32` just runs out of precision.
There is likely a better solution to the problem.
Fixes #1368
> Fix numerical issue on SVD with near-identity matrix

- src/base/matrix_view.rs
Fixed a (presumed) typo in documentation in matrix_view.rs.
Previously it says fixed_view and fixed_slice returns a matrix with `(R::dim(), CView::dim())` consecutive components. I just changed R to RView, because presumably this is a typo.
This is my first time submitting a pull request, and I would be more than happy to take any input.
> Fixed a (presumed) typo in documentation in matrix_view.rs

- src/base/storage.rs
As already discussed in https://github.com/dimforge/nalgebra.org/pull/86, there is a false statement in the documentation of the RawStorage trait.
In the documentation of RawStorage::stride it was falsely claimed that the storage of the matrix happens in a row-major fashion. In fact it is column-major.
> Fix false row-major comment in doc

- src/linalg/inverse.rs
- tests/core/matrix.rs
Fixes #1380 
Modified the `do_inverse4` function to calculate the determinant of 4x4 matrix before proceeding with the computation of the adjugate matrix to ensure that `out` is not modified if the determinant is zero.
> Inverting a 4x4 matrix with `try_inverse_mut` doesn't leave `self` unchanged if the inversion fails.

- src/base/array_storage.rs
This fixes a typo in the `ArrayStorage` documentation comment. 
It currently says "A array-based statically sized matrix data storage", the fix is to say "An array-based [...]".
> Fix typo in ArrayStorage documentation comment

- nalgebra-macros/Cargo.toml
> Update syn to `2.0`

- src/base/array_storage.rs
- src/base/default_allocator.rs
- src/base/matrix_view.rs
- src/base/storage.rs
- src/base/vec_storage.rs
This is a rebased version of #1379 so I can include it in today’s release without bothering the author. I wasn’t able to push directly to the PR’s branch, likely because it has been disabled when opening the PR.
Hopefully git/github should be smart enough to preserve authorship here.
> Introduce Storage::forget_elements() to fix memory leak in Matrix::generic_resize()

- CHANGELOG.md
- Cargo.toml
- README.md
- examples/cargo/Cargo.toml
- nalgebra-glm/Cargo.toml
- nalgebra-lapack/Cargo.toml
- nalgebra-macros/Cargo.toml
- nalgebra-sparse/Cargo.toml
- Fix a memory leak in `Matrix::generic_resize`.
- Fix `glm::is_null` to check the vector magnitude instead of individual components.
- Ensure that inverting a 4x4 matrix leaves it unchanged if the inversion fails.
- Add the `glam-0.28` feature to enable conversion from/to types from `glam` v0.28.
- Add a `stack!` macro for concatenating matrices. See [#1375](https://github.com/dimforge/nalgebra/pull/1375).
- The `cuda` feature has been removed, as the toolchain it depends on is long abandoned.
- Update to `simba` 0.9. See the [changelog](https://github.com/dimforge/simba/blob/master/CHANGELOG) of `simba` for details.
- Update the `nalgebra-macros` crate to `syn` 2.0.
- Remove the scalar type `T` from the `Allocator` trait parameters. Instead of `Allocator<T, R, C>`, use the simpler …
> Release v0.33.0

- CHANGELOG.md
- Cargo.toml
- src/base/matrix.rs
- src/geometry/isometry.rs
- src/geometry/similarity.rs
- tests/core/conversion.rs
- Add implementations of bytemuck traits for isometries and similarities.
- Implement `AsRef<[T]>` for matrices with contiguous storage.
- Enable the `num-complex/bytemuck` feature when the `convert-bytemuck` feature is enabled.
> feat: implement bytemuck traits for isometries and similarities

- src/base/edition.rs
- src/base/matrix.rs
- src/geometry/dual_quaternion.rs
- src/geometry/isometry_construction.rs
- src/geometry/quaternion.rs
- src/geometry/quaternion_construction.rs
- src/geometry/rotation_interpolation.rs
- src/geometry/rotation_specialization.rs
- src/geometry/similarity_construction.rs
- src/linalg/decomposition.rs
- src/linalg/schur.rs
- src/linalg/svd.rs
- src/linalg/symmetric_eigen.rs
This is a new warning in Rust 1.80's clippy that will be released this week.
> clippy: Fix `clippy::doc_lazy_continuation` lints

- CHANGELOG.md
- Cargo.toml
- Add the `convert-glam029` feature to enable conversion from/to types from `glam` v0.29.
> Release v0.33.2

- src/base/edition.rs
Matrix::fill_upper_triangle currently says that it "Sets all the elements of the _lower_-triangular part...", when it should say it fills the "_upper_-triangular part"
> Fix comment on Matrix::fill_upper_triangle

- Cargo.toml
- src/base/construction.rs
- src/base/helper.rs
- src/geometry/isometry_construction.rs
- src/geometry/orthographic.rs
- src/geometry/perspective.rs
- src/geometry/point_construction.rs
- src/geometry/quaternion_construction.rs
- src/geometry/rotation_specialization.rs
- src/geometry/scale_construction.rs
- src/geometry/similarity_construction.rs
- src/geometry/translation_construction.rs
- src/geometry/unit_complex_construction.rs
- tests/core/helper.rs
- tests/linalg/cholesky.rs
- tests/linalg/exp.rs
Bumps the `rand` version.
Things of note:
- `new_random_generic` in `base::construction` used `thread_rng`.  This function is now locked under a `thread_rng` feature, so I added it to nalgebra's `rand`.
> Upgrade `rand` to 0.9.0

- .github/workflows/nalgebra-ci-build.yml
- tests/macros/trybuild/stack_incompatible_block_dimensions.stderr
- tests/macros/trybuild/stack_incompatible_block_dimensions2.stderr
Criterion brings `half` crate which Minimum Supported Rust Version is 1.81, so CI is failing, let's discuss how to fix:
- I bumped rust version and kept a check on MSRV.
- I updated the expected error message for rust 1.81 ; https://github.com/dimforge/nalgebra/pull/1504 may be relevant
I removed the warning to errors, let's see how it goes.
> Fix CI: `half` requiring rust 1.81

- CHANGELOG.md
- src/linalg/schur.rs
- tests/linalg/schur.rs
This PR fixes #1291, by adding a check to avoid a 0/0 division in `Schur.do_decompose()` which was causing the decomposition to hang. The decomposition now works correctly for zero matrices (giving the identity for $Q$ and the zero matrix for $T$).
> Fixes the Schur decomposition for a zero matrix

- CHANGELOG.md
- Cargo.toml
- examples/cargo/Cargo.toml
- nalgebra-glm/Cargo.toml
- nalgebra-lapack/Cargo.toml
- nalgebra-macros/Cargo.toml
- nalgebra-sparse/Cargo.toml
- Add the `convert-glam030` feature to enable conversion from/to types from `glam` v0.30.
- Add the `defmt` cargo feature that enables derives of `defmt::Format` for all no-std types.
- Bumped MSRV to 1.87.0.
- Updated rand dependency to 0.9.0.
- Renamed associated const `DimName::USIZE` to `DimName::DIM`.
- Moved to Rust 2024 edition.
- Several methods are now `const` whenever possible. See details in [#1522](https://github.com/dimforge/nalgebra/pull/1522).
- Features for conversion from/to types from `glam` (such as `convert-glam029`) no longer enable default features for
`glam`, allowing use in `no_std` environments.
- Fix infinite loop when attempting to take the Schur decomposition of a 0 matrix.
> Release v0.34.0

- .github/workflows/nalgebra-ci-build.yml
- benches/linalg/bidiagonal.rs
- benches/linalg/full_piv_lu.rs
- benches/linalg/hessenberg.rs
- benches/linalg/lu.rs
- benches/linalg/qr.rs
This fixes following warnings:
```text
warning: function `bidiagonalize_500x500` is never used
--> benches/linalg/bidiagonal.rs:35:4
|
35 | fn bidiagonalize_500x500(bh: &mut criterion::Criterion) {
|    ^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
warning: function `bidiagonalize_unpack_500x500` is never used
--> benches/linalg/bidiagonal.rs:73:4
|
73 | fn bidiagonalize_unpack_500x500(bh: &mut criterion::Criterion) {
|    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
warning: function `full_piv_lu_decompose_500x500` is never used
--> benches/linalg/full_piv_lu.rs:18:4
|
18 | fn full_piv_lu_decompose_500x500(bh: &mut criterion::Criterion) {
|    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
warning: function `full_piv_lu_solve_500x500` is never used
--> benches/linalg/full_piv_lu.rs:49:4
|
49 | fn …
```
> Fix linalg bench warnings

- Cargo.toml
Building `nalgebra` with `glam` in `no_std` environments currently fails with "You must specify a math backend. Consider enabling either `std`, `libm`, or `nostd-libm`.". This PR forwards the `libm` feature to the `glam` dependency such that building in `no_std` environments succeeds now:
```rust
cargo build --target thumbv7m-none-eabi --no-default-features --features convert-glam030,libm
```
The chosen target is a `no_std` environment.
> Fix build with `glam` in `no_std` environments.
