dimforge/nalgebra

src/lib.rs, src/structs/dmat.rs, src/structs/dvec.rs, src/structs/dvec_macros.rs, src/structs/spec/vec.rs, src/structs/spec/vec0.rs, src/structs/vec_macros.rs, src/traits/geometry.rs, src/traits/structure.rs
=> Remove obsolete closure syntax

src/lib.rs, src/structs/dvec.rs, src/structs/dvec_macros.rs, src/structs/pnt.rs, src/structs/quat.rs, src/structs/spec/vec0.rs, src/structs/vec.rs, src/structs/vec_macros.rs
This fixes the build on `rustc 1.0.0-nightly (522d09dfe 2015-02-19) (built 2015-02-20)` for me.
=> FromIterator changes and phantom type annotations.

src/structs/dmat.rs, src/structs/dvec_macros.rs, src/structs/mat_macros.rs, tests/mat.rs, tests/quat.rs, tests/vec.rs
Nightly fixes from my previous PR without the FFI stuff. Also fixes the deprecated closure syntax that just showed up in the latest nightly.
=> Nightly fixes

Cargo.toml, src/structs/dvec_macros.rs, src/structs/mat_macros.rs, tests/assert.rs
Also fixed all deprecation warnings.
=> Update for rustc

src/lib.rs, src/structs/dmat.rs, src/structs/dvec_macros.rs
=> Update to latest nightly

benches/dmat.rs, benches/mat.rs, benches/quat.rs, benches/vec.rs
The extern crate declarations had to be adjusted.
=> Fix benchmarks

src/lib.rs, src/traits/structure.rs
Addresses part of the issues in #108.
=> Partial stabilization to Rust 1.0

src/lib.rs, src/structs/ortho.rs, src/structs/quat.rs, src/traits/structure.rs
=> Remove #![feature(core)]

src/traits/operations.rs
changes the remaining std::num -> num
=> fixes for latest rust

src/structs/dmat.rs, tests/mat.rs
=> Add pointwise addition and subtraction for `DMat`.

src/structs/dmat.rs, tests/mat.rs
Fixes #142 and adds a test for it.
=> Fix multiplication of rectangular DMats

README.md
=> Add Travis badge to the README.

src/lib.rs, src/linalg/decompositions.rs, src/linalg/mod.rs, tests/mat.rs
I implemented the Cholesky decomposition for square symmetric positive definite matrices which size is known at compile time. As with the QR decomposition, DMat is not yet supported.
=> Implemented Cholesky decomposition

src/structs/dmat.rs, tests/mat.rs
And add a test for it. Closes #148.
=> Fix transpose_mut for square matrices.

src/structs/iso.rs, src/structs/rot.rs
https://github.com/sebcrozet/nalgebra/issues/154
=> Fixed issue #154 https://github.com/sebcrozet/nalgebra/issues/154

src/structs/dmat.rs, tests/mat.rs
=> Implement Row & Col Traits for DMat

Cargo.toml, benches/dmat.rs, src/lib.rs, src/structs/dmat.rs, src/structs/dmat_macros.rs, src/structs/dvec.rs, src/structs/dvec_macros.rs, src/structs/mat.rs, src/structs/mat_macros.rs, src/structs/mod.rs, src/structs/vec.rs, src/structs/vec_macros.rs, src/traits/operations.rs, tests/mat.rs, tests/quat.rs, tests/vec.rs
This fixes several other issues. See individual commits for more details.
=> Implement stack-allocated matrices with small bounded dynamic sizes.

src/lib.rs, src/structs/pnt_macros.rs, src/traits/structure.rs
This PR aims to solve #177. 
Do note that PR #126 also moves nalgebra to associated types, however PntAsVec is not included there.
=> Made PntAsVec use associated types.

README.md, src/structs/dmat.rs, src/structs/dmat_macros.rs, src/structs/dvec.rs, src/structs/iso.rs, src/structs/iso_macros.rs, src/structs/mat.rs, src/structs/mat_macros.rs, src/structs/pnt.rs, src/structs/pnt_macros.rs, src/structs/quat.rs, src/structs/rot.rs, src/structs/rot_macros.rs, src/structs/sim.rs, src/structs/sim_macros.rs, src/structs/spec/mat.rs, src/structs/vec.rs, src/structs/vec_macros.rs, src/structs/vecn.rs, src/structs/vecn_macros.rs, src/traits/structure.rs, tests/op_assign.rs
=> Implement `*Assign` traits.

src/structs/dvec.rs, tests/mat.rs
=> Implement Outer for DVec.

src/structs/matrix_macros.rs, src/structs/vector_macros.rs
=> Implement From returning a value (instead of a ref only) for matrices and vectors.

src/structs/common_macros.rs
Implements operations for references.
Examples:
- `&Vector3<F> * F`
- `Vector3<F> * &F`
- `&Vector3<F> * &F`
- `-&Vector3<F>`
=> implement common operations for references

Cargo.toml, src/core/conversion.rs, tests/conversion.rs
They were mistakenly removed or incomplete.
Fix #223 #160 #36
=> Implement AsRef, AsMut, Into, From for matrices.

CHANGELOG.md, src/core/matrix.rs, tests/matrix.rs
=> Add a method to compute the trace of a matrix.

CHANGELOG.md, src/core/ops.rs, tests/matrix.rs
=> Add kronecker product.

src/core/ops.rs, tests/matrix.rs
=> Implement the sum and product traits for matrices

src/core/conversion.rs, tests/conversion.rs
=> De-ambiguate AsRef/AsMut/Into implementations.

src/geometry/transform.rs
=> Fix TCategory implementation for TAffine

.travis.yml, Cargo.toml, src/core/conversion.rs, src/geometry/quaternion_conversion.rs, src/geometry/rotation_conversion.rs, src/lib.rs, tests/core/conversion.rs, tests/core/mint.rs, tests/core/mod.rs, tests/lib.rs
see https://github.com/kvark/mint
=> Mint integration

.travis.yml, tests/core/blas.rs, tests/core/conversion.rs, tests/core/matrix.rs, tests/core/serde.rs, tests/geometry/isometry.rs, tests/geometry/point.rs, tests/geometry/projection.rs, tests/geometry/quaternion.rs, tests/geometry/rotation.rs, tests/geometry/similarity.rs, tests/geometry/unit_complex.rs, tests/linalg/balancing.rs, tests/linalg/bidiagonal.rs, tests/linalg/cholesky.rs, tests/linalg/eigen.rs, tests/linalg/full_piv_lu.rs, tests/linalg/hessenberg.rs, tests/linalg/lu.rs, tests/linalg/qr.rs, tests/linalg/real_schur.rs, tests/linalg/solve.rs, tests/linalg/svd.rs, tests/linalg/tridiagonal.rs
Addresses #289.
There are still a lot of warnings. I would like to fix those before merging.
=> Let the test suite run with no features

src/core/matrix.rs, tests/core/matrix.rs
=> Remove phantom data from matrix debug output

CHANGELOG.md, src/core/construction.rs, src/geometry/quaternion.rs, src/geometry/quaternion_construction.rs
=> Add UnitQuaternion::{new_eps, from_scaled_axis_eps}.

CHANGELOG.md, src/core/construction_slice.rs, src/core/construction_slice_deprecated.rs, src/core/mod.rs, src/geometry/isometry_alga.rs, src/geometry/isometry_ops.rs, src/geometry/unit_complex_ops.rs, src/lib.rs, tests/core/matrix_slice.rs
=> Incoherent fundamental impls

src/geometry/point_conversion.rs
=> Adds conversions to and from mint Point types.

src/base/dimension.rs, src/base/matrix_slice.rs
=> Implement Send + Sync for SliceStorage{Mut}.

src/base/alias.rs
M-by-N matrices are not square when M != N
=> Fixed error in comments

CHANGELOG.md, src/base/matrix.rs, tests/core/matrix.rs
=> Add a copy_from_slice method.

src/geometry/transform_ops.rs
The scaling did not occur at the right time.
Fix #394
=> Fix projective * point multiplication.

src/base/matrix.rs, tests/core/matrix.rs
=> Fix partial_clamp for vectors/matrices.

nalgebra-glm/src/geometric.rs, nalgebra-glm/src/gtx/norm.rs, nalgebra-glm/src/lib.rs, src/base/dimension.rs, src/lib.rs
I think this is a good start on how the docs could improve. I'll keep doing more of this if you like this direction.
=> Improve cross-linking and cross-referencing in docs.

src/base/alias.rs
Hello,
I just spotted a few typos in the descriptions of Matrix types, so here's a quick fix.
Thanks a lot for making nalgebra!
Thomas
=> Fix minor typos

nalgebra-glm/src/ext/matrix_clip_space.rs
=> Fix glm::perspective.

nalgebra-glm/src/common.rs
=> Fix the glm::sign function to match its documentation.

src/geometry/isometry.rs, src/geometry/isometry_alias.rs
=> Use other keywords for isometry documentations.

ci/test.sh
=> Run CI tests on nalgebra-glm too.

src/base/matrix.rs
=> Add lerp to vectors.

src/base/cg.rs
Addresses https://github.com/rustsim/nalgebra/issues/372
=> Make MatrixN::{transform_vector, transform_point} inherent methods.

CHANGELOG.md, nalgebra-glm/src/gtc/type_ptr.rs, src/geometry/isometry_alga.rs, src/geometry/isometry_construction.rs, src/geometry/isometry_conversion.rs, src/geometry/isometry_ops.rs, src/geometry/point_construction.rs, src/geometry/quaternion.rs, src/geometry/quaternion_alga.rs, src/geometry/quaternion_construction.rs, src/geometry/quaternion_conversion.rs, src/geometry/quaternion_ops.rs, src/geometry/similarity.rs, src/geometry/similarity_construction.rs, src/geometry/similarity_conversion.rs, src/geometry/similarity_ops.rs, src/geometry/translation.rs, src/geometry/translation_alga.rs, src/geometry/translation_alias.rs, src/geometry/translation_construction.rs, src/geometry/translation_conversion.rs, src/geometry/translation_ops.rs, src/geometry/unit_complex_ops.rs
This adds doc-tests for Translation, Quaternion, and UnitQuaternion.
=> Documentation improvements.

src/geometry/orthographic.rs
=> Remove over-restrictive assertions on Orthographic3 construction + add doc-tests

examples/linear_system_resolution.rs
This is the example matching https://github.com/rustsim/nalgebra.org/pull/20
=> Add an example for the resolution of a linear system.

src/geometry/rotation_specialization.rs, tests/geometry/rotation.rs
=> Fix cornercase for Rotation3 conversion to euler angles.

src/lib.rs
Implements #371. Work-in-progress.
=> Deprecate free functions

nalgebra-glm/Cargo.toml, nalgebra-glm/src/lib.rs
=> Forward features from nalgebra-glm to its nalgebra dependency.

src/base/matrix.rs, tests/core/matrix.rs
=> Add `push` method to Vector

CHANGELOG.md, src/base/construction.rs, src/base/vec_storage.rs
=> Remove the Deref implementation for MatrixVec

Cargo.toml, src/geometry/quaternion.rs, src/geometry/quaternion_construction.rs
The test values are based on qtfm.
=> quaternion trigonometry

src/base/cg.rs, src/base/edition.rs
=> Fix two compiler warnings

src/geometry/quaternion.rs
I have implemented the solution discussed in #543.
=> Using atan2 instead of acos for rotation angles.

tests/core/serde.rs
=> Add tests for serialization of 2D transformations.

src/base/ops.rs
I have also added a test to the documentation, although I'm not 100% sure that's the right place to put them.
Let me know if I can improve something for this PR.
=> Allow getting .min() and .max() of matrices of unsigned integers

src/base/blas.rs, tests/core/empty.rs, tests/core/mod.rs
=> Fix UB when multiplying empty matrices.

src/base/matrix.rs
It's a simple one, but working with usually either huge or very small floats, I've really been missing this format.
It's basically just a copy-paste of the Display implementation, but using the LowerExp formater for values.
=> Implemented LowerExp for Matrix

src/linalg/cholesky.rs, src/linalg/full_piv_lu.rs, src/linalg/qr.rs
see issue 667 : https://github.com/rustsim/nalgebra/issues/667
=> insured Storage trait is used in solve methods

src/base/iter.rs
After we yield the final element from the iterator, we don't offset
`ptr` agian, to avoid having it go out-of-bounds.
However, `inner_end` may be several elements out-of-bounds, depending on
the value of `size`. Therefore, we use `wrapping_offset` to avoid
undefined behavior.
Found using Miri
=> Fix some out-of-bounds `offset` calls

src/base/conversion.rs
=> Add matrix/slice conversions.

CHANGELOG.md
=> Update the changelog.

src/base/conversion.rs, src/base/default_allocator.rs, src/base/dimension.rs, src/base/storage.rs, tests/core/matrix.rs, tests/linalg/inverse.rs
Should be very straightforward :)
=> Fix warnings on latest rustc

src/base/matrix.rs
- Supplement the document of fn vector_to_matrix_index
- Supplement the document of fn as_ptr
=> Supplement the document of base/matrix

tests/core/conversion.rs, tests/core/matrix.rs
Hello! I was trying to do a little work on building out real nonsymmetric eigendecomposition and ran into test compile errors for these two files when I ran 
`cargo +nightly test --features "arbitrary, debug"`
Thank you for all your fantastic crates!
=> Fix alga cfg gate for some quickcheck tests.

src/geometry/quaternion_construction.rs
Tried to add a comment on why this is returns an Option.
=> Why Option<_>

src/linalg/exp.rs, tests/linalg/exp.rs
=> Add matrix exponential for complex matrices

src/base/blas.rs
=> Add missing dot-product dimension check.

.circleci/config.yml
Clippy job will not fail anymore once PR https://github.com/dimforge/nalgebra/pull/783 is merged.
=> circleci: add clippy job

src/lib.rs
=> update the version number in the documentation

Cargo.toml, src/base/array_storage.rs, src/base/matrix.rs, src/base/unit.rs, src/geometry/point.rs, src/geometry/quaternion.rs
=> Added bytemuck implementations for static storages.

src/base/alias.rs
=> Add type aliases for unit vectors

src/base/componentwise.rs
Add doc test for `inf`, `sup`, `inf_sup`, `add_scalar` and `add_scalar_mut`.
(Note: This is my first PR here!)
=> add missing doc tests

src/base/storage.rs
=> Fixed potential UB

src/geometry/transform.rs
This just fixes the types in the existing TODO to compile.
=> impl Hash for Transform

src/geometry/dual_quaternion.rs, src/geometry/orthographic.rs, src/geometry/perspective.rs, src/geometry/quaternion.rs, src/geometry/rotation_specialization.rs, src/geometry/unit_complex.rs
I screwed up #918 pretty badly, this PR does what that one was supposed to do.
=> `&self` → `self` on `Copy` types.

src/geometry/orthographic.rs, src/geometry/point.rs
=> Fix a few bitrotted user guide links

src/geometry/transform_ops.rs
... following the same implementation strategy as was used for `UnitQuaternion`.
=> Add Transform × UnitComplex & friends

src/geometry/mod.rs, src/geometry/reflection.rs, src/geometry/reflection_alias.rs
Also consistently use "reflection" over "reflexion".
=> Add bias getter and alias for reflection.

CHANGELOG.md, src/base/conversion.rs, src/base/matrix.rs
Related to request #975 
Maybe I am missing some documentation somewhere, like the Changelog? Let me know and I fix it.
=> Implement conversion methods for RowDVector

CHANGELOG.md, Cargo.toml, src/third_party/glam/mod.rs, src/third_party/glam/v018/mod.rs
I copied #965 and adjusted it for glam 0.18.
=> Implement conversion traits for glam 0.18

src/linalg/exp.rs
Gives a little performance improvement (-13% for `Matrix3`, -21% for `Matrix2`, -0% for `Matrix1`).
=> exp.rs: factorial(): use precomputed factorial array

src/base/indexing.rs, src/base/matrix_slice.rs
=> fix linear indexing of matrix slices

.github/workflows/nalgebra-ci-build.yml, nalgebra-glm/src/traits.rs
=> Fix nalgebra-glm no-std CI build

src/base/conversion.rs
=> Re-add the conversion from a vector/matrix slice to a static array

src/linalg/svd.rs, tests/linalg/svd.rs
Fixes the SVD bug in #983 and introduces a new test covering it.
=> Fix SVD instability bug

.github/workflows/nalgebra-ci-build.yml, Cargo.toml, src/base/array_storage.rs, src/base/dimension.rs, src/base/matrix.rs, src/base/unit.rs, src/geometry/dual_quaternion.rs, src/geometry/isometry.rs, src/geometry/orthographic.rs, src/geometry/perspective.rs, src/geometry/point.rs, src/geometry/quaternion.rs, src/geometry/rotation.rs, src/geometry/scale.rs, src/geometry/similarity.rs, src/geometry/transform.rs, src/geometry/translation.rs, src/geometry/unit_complex.rs
=> Update to cust 0.3

nalgebra-sparse/src/lib.rs, src/base/allocator.rs, src/base/construction.rs, src/base/default_allocator.rs, src/lib.rs
This is #1082 with some simplifications to avoid code duplication.
=> Sound implementation of from row iterator

src/geometry/point_construction.rs
Based on my brief testing, these two changed lines are all that is needed to make this work.
=> Make "Point::new" a const fn

src/geometry/point_construction.rs
=> Add a non-const version of Point::new when the cuda feature is enabled

.github/workflows/nalgebra-ci-build.yml, Cargo.toml, src/base/array_storage.rs, src/base/dimension.rs, src/base/matrix.rs, src/base/mod.rs, src/base/rkyv_wrappers.rs, src/base/unit.rs, src/geometry/dual_quaternion.rs, src/geometry/isometry.rs, src/geometry/orthographic.rs, src/geometry/perspective.rs, src/geometry/point.rs, src/geometry/quaternion.rs, src/geometry/rotation.rs, src/geometry/scale.rs, src/geometry/similarity.rs, src/geometry/translation.rs, src/lib.rs, tests/core/mod.rs, tests/core/rkyv.rs
This is a follow-up on #1128 which I merged by mistake.
=> Make sure Archive types are Self

src/geometry/rotation_specialization.rs
This fixes https://github.com/dimforge/nalgebra/issues/1170
=> Fix typo in `euler_angles()`, and cache cosine computation.

src/linalg/inverse.rs
Hi there,
I was assuming that `try_*` method is not suppose to panic, so initially I intended to make it return `false` but then decided to just create a comment.
What do you think?
=> update try_inverse doc comment

nalgebra-glm/src/gtc/epsilon.rs, nalgebra-glm/src/gtx/quaternion.rs, nalgebra-sparse/src/cs.rs, nalgebra-sparse/src/ops/serial/csc.rs, nalgebra-sparse/src/ops/serial/csr.rs, src/base/allocator.rs, src/base/edition.rs, src/base/iter.rs, src/base/par_iter.rs, src/base/uninit.rs, src/base/vec_storage.rs, src/geometry/isometry_interpolation.rs, src/geometry/quaternion.rs, src/geometry/transform.rs, src/geometry/unit_complex.rs, src/linalg/svd.rs, src/sparse/cs_matrix.rs, tests/linalg/eigen.rs
This revision includes:
- Correct minor typos
=> Correct minor typos

src/base/alias.rs
Correct the documentation according to Github discussion https://github.com/dimforge/nalgebra/discussions/1225
=> docs: correct row-major -> column-major for Matrix{1-6}xX storage

Cargo.toml, src/third_party/glam/mod.rs, src/third_party/glam/v024/mod.rs
Based on previous glam version PR #1213
=> Adds support for glam 0.24

src/base/interpolation.rs, src/geometry/point.rs
I wasn’t sure where to put this method, but I decided that `base/interpolation.rs` was a good place.
=> Add OPoint::lerp

src/geometry/dual_quaternion.rs, src/geometry/quaternion.rs, src/lib.rs
When testing for something, need to use the assert form.
=> Use `assert_relative_eq!` instead of relative_eq!`.

nalgebra-glm/src/vector_relational.rs
=> Correct less than or equal symbol in doc in vector_relational.rs

src/base/storage.rs
Resolves https://github.com/dimforge/nalgebra/issues/1217
=> docs: fix documentation on strides

src/base/construction.rs
=> Clarify documentation for `from_fn`

CHANGELOG.md, Cargo.toml, src/third_party/encase/mod.rs, src/third_party/mod.rs
Resolves https://github.com/dimforge/nalgebra/issues/1513 & https://github.com/teoxoy/encase/issues/104.
=> Add `encase` trait implementations

CHANGELOG.md, Cargo.toml
* Added `encase` feature, providing `encase` trait implementations for `nalgebra` types.
=> Release v0.34.1
